#include "SqlProvider.h"
#include <duckdb.h>
#include <chrono>
#include <thread>
#include <condition_variable>
#include <sstream>
#include <filesystem>
namespace native_app {
namespace {
struct Database { duckdb_database value=nullptr; explicit Database(const ConnectionProfile& p) { duckdb_config config=nullptr; if(duckdb_create_config(&config)==DuckDBError)throw std::runtime_error("Cannot configure DuckDB.");
  try{auto apply=[&](const nlohmann::json& options){if(!options.is_object())throw std::runtime_error("DuckDB config must be a JSON object.");for(auto option=options.begin();option!=options.end();++option){if(!option.value().is_string()&&!option.value().is_boolean()&&!option.value().is_number())throw std::runtime_error("DuckDB configuration values must be strings, booleans, or numbers.");const auto value=option.value().is_string()?option.value().get<std::string>():option.value().dump();if(option.key().find('\0')!=std::string::npos||value.find('\0')!=std::string::npos||duckdb_set_config(config,option.key().c_str(),value.c_str())==DuckDBError)throw std::runtime_error("Unsupported or invalid native DuckDB configuration option: "+option.key());}};
   const auto options=nlohmann::json::parse(p.optionsJson);for(auto option=options.begin();option!=options.end();++option){if(option.key()=="config")apply(option.value());else apply(nlohmann::json{{option.key(),option.value()}});}if(p.readOnly&&duckdb_set_config(config,"access_mode","READ_ONLY")==DuckDBError)throw std::runtime_error("Cannot enforce DuckDB read-only mode.");
  }catch(...){duckdb_destroy_config(&config);throw;}
  char* error=nullptr;const auto status=duckdb_open_ext(p.path.c_str(),&value,config,&error);duckdb_destroy_config(&config);std::string message=error?error:"Cannot open DuckDB file.";duckdb_free(error);if(status==DuckDBError)throw std::runtime_error(message); }~Database(){if(value)duckdb_close(&value);} };
struct Connection { duckdb_connection value=nullptr;explicit Connection(Database& db){if(duckdb_connect(db.value,&value)==DuckDBError)throw std::runtime_error("Cannot connect to DuckDB.");}~Connection(){duckdb_disconnect(&value);} };
struct Result { duckdb_result value{};~Result(){duckdb_destroy_result(&value);} };
struct PreparedHandle {duckdb_prepared_statement value=nullptr;~PreparedHandle(){duckdb_destroy_prepare(&value);} };
struct Extracted {duckdb_extracted_statements value=nullptr;~Extracted(){duckdb_destroy_extracted(&value);} };
class InterruptGuard {public:InterruptGuard(duckdb_connection db,const std::atomic_bool* cancellation,int timeout):db_(db){worker_=std::thread([this,cancellation,timeout]{std::unique_lock<std::mutex> lock(mutex_);const auto deadline=std::chrono::steady_clock::now()+std::chrono::seconds(timeout);while(!done_){if((cancellation&&cancellation->load())||std::chrono::steady_clock::now()>=deadline){duckdb_interrupt(db_);break;}changed_.wait_for(lock,std::chrono::milliseconds(20));}});}~InterruptGuard(){{std::lock_guard<std::mutex> lock(mutex_);done_=true;}changed_.notify_all();if(worker_.joinable())worker_.join();}private:duckdb_connection db_;std::mutex mutex_;std::condition_variable changed_;bool done_=false;std::thread worker_;};
DbValue Value(duckdb_result* result,idx_t column,idx_t row){if(duckdb_value_is_null(result,column,row))return {DbValueType::Null,""};const auto type=duckdb_column_type(result,column);
 if(type==DUCKDB_TYPE_BOOLEAN)return {DbValueType::Boolean,duckdb_value_boolean(result,column,row)?"true":"false"};
 if(type==DUCKDB_TYPE_TINYINT||type==DUCKDB_TYPE_SMALLINT||type==DUCKDB_TYPE_INTEGER||type==DUCKDB_TYPE_BIGINT||type==DUCKDB_TYPE_UTINYINT||type==DUCKDB_TYPE_USMALLINT||type==DUCKDB_TYPE_UINTEGER)return {DbValueType::Integer,std::to_string(duckdb_value_int64(result,column,row))};
 if(type==DUCKDB_TYPE_FLOAT||type==DUCKDB_TYPE_DOUBLE){std::ostringstream text;text<<std::setprecision(17)<<duckdb_value_double(result,column,row);return {DbValueType::Real,text.str()};}
 if(type==DUCKDB_TYPE_BLOB){const auto blob=duckdb_value_blob(result,column,row);std::string bytes;if(blob.size)bytes.assign(static_cast<const char*>(blob.data),static_cast<size_t>(blob.size));duckdb_free(blob.data);return {DbValueType::Blob,bytes};}
 const auto value=duckdb_value_string(result,column,row);std::string text;if(value.data)text.assign(value.data,static_cast<size_t>(value.size));duckdb_free(value.data);return {DbValueType::Text,text};
}
void Bind(duckdb_prepared_statement statement,const std::vector<DbValue>& values){for(size_t i=0;i<values.size();++i){const auto& value=values[i];duckdb_state state=DuckDBError;const auto index=static_cast<idx_t>(i+1);switch(value.type){case DbValueType::Null:state=duckdb_bind_null(statement,index);break;case DbValueType::Integer:state=duckdb_bind_int64(statement,index,DbValueJson(value).get<int64_t>());break;case DbValueType::Real:state=duckdb_bind_double(statement,index,DbValueJson(value).get<double>());break;case DbValueType::Boolean:state=duckdb_bind_boolean(statement,index,DbValueJson(value).get<bool>());break;case DbValueType::Blob:state=duckdb_bind_blob(statement,index,value.text.data(),value.text.size());break;default:{const auto text=value.type==DbValueType::Json?DbValueJson(value).dump():value.text;state=duckdb_bind_varchar_length(statement,index,text.data(),text.size());break;}}if(state==DuckDBError)throw std::runtime_error("DuckDB rejected a bound value.");}}
class DuckDbProvider final:public SqlProvider {
public:using SqlProvider::SqlProvider;
 void Test(const std::atomic_bool* cancellation)override {RequireNotCancelled(cancellation);if(!std::filesystem::is_regular_file(std::filesystem::u8path(profile_.path))&&!profile_.create)throw std::runtime_error("DuckDB database file does not exist.");Database db(profile_);Connection connection(db);RequireNotCancelled(cancellation);}
 QueryResult Query(const std::string& query,int rows,const std::atomic_bool* cancellation)override{return PreparedQuery(query,{},std::clamp(rows,1,100000),cancellation);}
 QueryResult Prepared(const std::string& query,const std::vector<DbValue>& values,int rows,const std::atomic_bool* cancellation)override{return PreparedQuery(query,values,rows,cancellation);}
 DatabaseSchema Schema(const std::atomic_bool* cancellation)override{
  DatabaseSchema schema;schema.databaseId=profile_.id;schema.databaseName=profile_.name;schema.dialect="duckdb";schema.capabilities=ProviderCapabilities("sql",profile_.readOnly,"duckdb");
  auto execute=[&](const std::string& sql,const std::vector<DbValue>& values){auto result=PreparedQuery(sql,values,10000,cancellation);if(!result.error.empty())throw std::runtime_error(result.error);if(result.truncated)throw std::runtime_error("DuckDB schema exceeds 10,000 objects.");return result;};
  const auto nameSpace=profile_.schema.empty()?"main":profile_.schema;const auto tables=execute("SELECT table_name, table_type FROM information_schema.tables WHERE table_schema = ? ORDER BY table_name",{{DbValueType::Text,nameSpace}});
  for(const auto& row:tables.rows){RequireNotCancelled(cancellation);TableMeta table;table.name=row.at("table_name");table.type=row.at("table_type")=="VIEW"?"view":"table";table.editable=table.type=="table"&&!profile_.readOnly;
   const std::vector<DbValue> parameters={{DbValueType::Text,nameSpace},{DbValueType::Text,table.name}};
   const auto columns=execute("SELECT column_name,data_type,ordinal_position,is_nullable,column_default FROM information_schema.columns WHERE table_schema = ? AND table_name = ? ORDER BY ordinal_position",parameters);
   for(const auto& item:columns.rows){ColumnMeta column;column.name=item.at("column_name");column.type=item.at("data_type");column.cid=std::stoi(item.at("ordinal_position"))-1;column.notnull=item.at("is_nullable")=="NO";if(item.at("column_default")!="NULL")column.dfltValue=item.at("column_default");table.columns.push_back(column);}
   const auto keys=execute("SELECT k.column_name FROM information_schema.table_constraints t JOIN information_schema.key_column_usage k ON t.constraint_catalog=k.constraint_catalog AND t.constraint_schema=k.constraint_schema AND t.constraint_name=k.constraint_name WHERE t.table_schema = ? AND t.table_name = ? AND t.constraint_type='PRIMARY KEY' ORDER BY k.ordinal_position",parameters);
   for(const auto& key:keys.rows){table.primaryKeys.push_back(key.at("column_name"));for(auto& column:table.columns)if(column.name==key.at("column_name"))column.pk=true;}
   const auto count=execute("SELECT COUNT(*) AS total FROM "+QuoteSqlIdentifier(nameSpace,"duckdb")+"."+Identifier(table.name),{});if(!count.rows.empty())table.rowCount=std::stoll(count.rows[0].at("total"));
   const auto ddl=execute(table.type=="view"?"SELECT sql FROM duckdb_views() WHERE schema_name=? AND view_name=?":"SELECT sql FROM duckdb_tables() WHERE schema_name=? AND table_name=?",parameters);if(!ddl.rows.empty())table.ddl=ddl.rows[0].at("sql");
   const auto indexes=execute("SELECT index_name,is_unique,expressions FROM duckdb_indexes() WHERE schema_name=? AND table_name=?",parameters);for(const auto& index:indexes.rows){IndexMeta item;item.name=index.at("index_name");item.unique=index.at("is_unique")=="true";item.origin="DuckDB";item.columns.push_back(index.at("expressions"));table.indexes.push_back(std::move(item));}
   const auto foreign=execute("SELECT constraint_column_names::JSON AS source, referenced_table, referenced_column_names::JSON AS target FROM duckdb_constraints() WHERE schema_name=? AND table_name=? AND constraint_type='FOREIGN KEY'",parameters);
   int id=0;for(const auto& key:foreign.rows){const auto source=nlohmann::json::parse(key.at("source")),target=nlohmann::json::parse(key.at("target"));for(size_t i=0;i<source.size()&&i<target.size();++i){ForeignKeyMeta item;item.id=id;item.seq=static_cast<int>(i);item.fromColumn=source[i].get<std::string>();item.toColumn=target[i].get<std::string>();item.targetTable=key.at("referenced_table");table.foreignKeys.push_back(std::move(item));}++id;}
   schema.tables.push_back(std::move(table));
  }return schema;
 }
private:
 QueryResult PreparedQuery(const std::string& query,const std::vector<DbValue>& values,int rows,const std::atomic_bool* cancellation){QueryResult result;result.query=query;const auto started=std::chrono::steady_clock::now();try{RequireNotCancelled(cancellation);if(profile_.readOnly)RequireReadOnlySql(query);Database db(profile_);Connection connection(db);InterruptGuard guard(connection.value,cancellation,profile_.timeoutSec);Extracted extracted;const auto count=duckdb_extract_statements(connection.value,query.c_str(),&extracted.value);if(const auto error=duckdb_extract_statements_error(extracted.value);error&&*error)throw std::runtime_error(error);if(!count)throw std::runtime_error("Enter a query.");if(!values.empty()&&count!=1)throw std::runtime_error("A prepared operation must contain one SQL statement.");
   bool transaction=count>1;const auto statements=SqlStatements(query);for(const auto& sql:statements){const auto first=sql.find_first_not_of(" \t\r\n");if(first!=std::string::npos){std::string word;for(size_t i=first;i<sql.size()&&isalpha(static_cast<unsigned char>(sql[i]));++i)word+=static_cast<char>(toupper(static_cast<unsigned char>(sql[i])));if(word=="BEGIN"||word=="COMMIT"||word=="ROLLBACK"||word=="PRAGMA"||word=="VACUUM"||word=="ATTACH"||word=="DETACH")transaction=false;}}
   if(transaction){Result begin;if(duckdb_query(connection.value,"BEGIN TRANSACTION",&begin.value)==DuckDBError)throw std::runtime_error(duckdb_result_error(&begin.value));}
   try{for(idx_t i=0;i<count;++i){RequireNotCancelled(cancellation);PreparedHandle prepared;if(duckdb_prepare_extracted_statement(connection.value,extracted.value,i,&prepared.value)==DuckDBError)throw std::runtime_error(duckdb_prepare_error(prepared.value));Bind(prepared.value,values);Result output;if(duckdb_execute_prepared(prepared.value,&output.value)==DuckDBError)throw std::runtime_error(duckdb_result_error(&output.value));RequireNotCancelled(cancellation);const auto affected=duckdb_rows_changed(&output.value);result.rowsAffected+=static_cast<int64_t>(affected);const auto type=duckdb_result_statement_type(output.value);const bool returnsRows=duckdb_result_return_type(output.value)==DUCKDB_RESULT_TYPE_QUERY_RESULT||type==DUCKDB_STATEMENT_TYPE_SELECT||type==DUCKDB_STATEMENT_TYPE_EXPLAIN||type==DUCKDB_STATEMENT_TYPE_PRAGMA||type==DUCKDB_STATEMENT_TYPE_CALL||(!affected&&duckdb_column_count(&output.value)>0&&duckdb_row_count(&output.value)>0);
     if(returnsRows){QueryResultSet set;set.query=query;set.rowsAffected=static_cast<int64_t>(affected);for(idx_t column=0;column<duckdb_column_count(&output.value);++column)set.columns.push_back(UniqueColumnLabel(duckdb_column_name(&output.value,column),set.columns));const auto size=duckdb_row_count(&output.value);set.truncated=size>static_cast<idx_t>(rows);for(idx_t row=0;row<std::min(size,static_cast<idx_t>(rows));++row){RequireNotCancelled(cancellation);TypedRow typed;std::map<std::string,std::string> display;for(idx_t column=0;column<set.columns.size();++column){auto value=Value(&output.value,column,row);display[set.columns[column]]=DbValueDisplay(value);typed[set.columns[column]]=std::move(value);}set.rows.push_back(std::move(display));set.typedRows.push_back(std::move(typed));}set.rowCount=static_cast<int64_t>(set.rows.size());result.columns=set.columns;result.rows=set.rows;result.typedRows=set.typedRows;result.rowCount=set.rowCount;result.truncated=set.truncated;result.resultSets.push_back(std::move(set));}}
    if(transaction){Result commit;if(duckdb_query(connection.value,"COMMIT",&commit.value)==DuckDBError)throw std::runtime_error(duckdb_result_error(&commit.value));}}
   catch(...){if(transaction){Result rollback;duckdb_query(connection.value,"ROLLBACK",&rollback.value);}throw;}
  }catch(const std::exception& error){result.error=cancellation&&cancellation->load()?"Query cancelled.":ScrubConnectionError(error.what(),profile_);result.rows.clear();result.typedRows.clear();result.columns.clear();result.resultSets.clear();result.rowsAffected=0;result.rowCount=0;}result.executionTimeMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();return result;
 }
};
}
std::shared_ptr<DatabaseProvider> CreateDuckDbProvider(const ConnectionProfile& profile){return std::make_shared<DuckDbProvider>(profile);}
}
