#include "NativeConnections.h"
#include "NativeSocket.h"
#include "DbValues.h"
#include <mongoc/mongoc.h>
#include <chrono>
#include <cerrno>
#include <mutex>
#include <set>
#include <functional>
namespace native_app {
namespace {
using json=nlohmann::json;
class Bson {public:bson_t* value=nullptr;explicit Bson(const json& document=json::object()){bson_error_t error{};const auto text=document.dump();value=bson_new_from_json(reinterpret_cast<const uint8_t*>(text.data()),static_cast<ssize_t>(text.size()),&error);if(!value)throw std::runtime_error(std::string("Invalid Mongo extended JSON: ")+error.message);}~Bson(){bson_destroy(value);}Bson(const Bson&)=delete;};
json Document(const bson_t* value){size_t count=0;char* text=bson_as_relaxed_extended_json(value,&count);if(!text)throw std::runtime_error("Mongo document could not be encoded.");try{auto result=json::parse(text,text+count);bson_free(text);return result;}catch(...){bson_free(text);throw;}}
struct TransportContext {const ConnectionProfile* profile;const std::atomic_bool* cancellation;std::string error;};
struct MongoStream {mongoc_stream_t base{};NativeSocket socket;TransportContext* context=nullptr;bool timedOut=false;};
MongoStream* Stream(mongoc_stream_t* stream){return reinterpret_cast<MongoStream*>(stream);}
void BSON_CALL Destroy(mongoc_stream_t* stream){delete Stream(stream);}
int BSON_CALL Close(mongoc_stream_t* stream){Stream(stream)->socket.Close();return 0;}
int BSON_CALL Flush(mongoc_stream_t*){return 0;}
ssize_t BSON_CALL Write(mongoc_stream_t* stream,mongoc_iovec_t* buffers,size_t count,int32_t){auto state=Stream(stream);try{size_t size=0;for(size_t i=0;i<count;++i){state->socket.Write(buffers[i].iov_base,buffers[i].iov_len);size+=buffers[i].iov_len;}return static_cast<ssize_t>(size);}catch(const std::exception& error){state->context->error=error.what();state->timedOut=state->context->error.find("timed out")!=std::string::npos;errno=state->timedOut?ETIMEDOUT:EIO;return -1;}}
ssize_t BSON_CALL Read(mongoc_stream_t* stream,mongoc_iovec_t* buffers,size_t count,size_t minimum,int32_t){auto state=Stream(stream);try{size_t total=0;for(size_t i=0;i<count;++i){size_t offset=0;while(offset<buffers[i].iov_len){const auto read=state->socket.Read(buffers[i].iov_base+offset,buffers[i].iov_len-offset);if(!read)return static_cast<ssize_t>(total);offset+=read;total+=read;if(total>=minimum)return static_cast<ssize_t>(total);}}return static_cast<ssize_t>(total);}catch(const std::exception& error){state->context->error=error.what();state->timedOut=state->context->error.find("timed out")!=std::string::npos;errno=state->timedOut?ETIMEDOUT:EIO;return -1;}}
int BSON_CALL Options(mongoc_stream_t*,int,int,void*,mongoc_socklen_t){return 0;}
mongoc_stream_t* BSON_CALL Base(mongoc_stream_t* stream){return stream;}
bool BSON_CALL Closed(mongoc_stream_t* stream){return !Stream(stream)->socket.Alive();}
bool BSON_CALL TimedOut(mongoc_stream_t* stream){return Stream(stream)->timedOut;}
bool BSON_CALL Retry(mongoc_stream_t*){return false;}
ssize_t BSON_CALL Poll(mongoc_stream_poll_t* streams,size_t count,int32_t){for(size_t i=0;i<count;++i){auto state=Stream(streams[i].stream);streams[i].revents=state->socket.Alive()?streams[i].events:0;if(state->context->cancellation&&state->context->cancellation->load()){state->context->error="Query cancelled.";errno=EIO;return -1;}}return static_cast<ssize_t>(count);}
mongoc_stream_t* BSON_CALL Initiate(const mongoc_uri_t* uri,const mongoc_host_list_t* host,void* data,bson_error_t* error){auto context=static_cast<TransportContext*>(data);std::unique_ptr<MongoStream> stream;mongoc_stream_t* secured=nullptr;try{RequireNotCancelled(context->cancellation);stream=std::make_unique<MongoStream>();stream->context=context;stream->base.type=1000;stream->base.destroy=Destroy;stream->base.close=Close;stream->base.flush=Flush;stream->base.writev=Write;stream->base.readv=Read;stream->base.setsockopt=Options;stream->base.get_base_stream=Base;stream->base.check_closed=Closed;stream->base.poll=Poll;stream->base.failed=Destroy;stream->base.timed_out=TimedOut;stream->base.should_retry=Retry;stream->socket.Connect(host->host,host->port,false,"",context->profile->timeoutSec,context->cancellation);
  if(mongoc_uri_get_tls(uri)){auto settings=*mongoc_ssl_opt_get_default();settings.ca_file=context->profile->sslCa.empty()?mongoc_uri_get_option_as_utf8(uri,"tlsCAFile",nullptr):context->profile->sslCa.c_str();settings.pem_file=mongoc_uri_get_option_as_utf8(uri,"tlsCertificateKeyFile",nullptr);settings.pem_pwd=mongoc_uri_get_option_as_utf8(uri,"tlsCertificateKeyFilePassword",nullptr);settings.weak_cert_validation=false;settings.allow_invalid_hostname=false;secured=mongoc_stream_tls_new_with_hostname(&stream->base,host->host,&settings,1);if(!secured)throw std::runtime_error("Cannot initialize native Mongo TLS.");stream.release();if(!mongoc_stream_tls_handshake_block(secured,host->host,context->profile->timeoutSec*1000,error))throw std::runtime_error(error->message);return secured;}
  return &stream.release()->base;
 }catch(const std::exception& failure){if(secured)mongoc_stream_destroy(secured);context->error=failure.what();bson_set_error(error,MONGOC_ERROR_STREAM,MONGOC_ERROR_STREAM_CONNECT,"%s",context->error.c_str());return nullptr;}}
void Initialize(){static std::once_flag once;std::call_once(once,[]{mongoc_init();mongoc_log_set_handler([](mongoc_log_level_t,const char*,const char*,void*){},nullptr);});}
struct Uri {mongoc_uri_t* value=nullptr;~Uri(){mongoc_uri_destroy(value);}};
struct Session {TransportContext transport;Uri uri;mongoc_client_t* client=nullptr;std::string database;
 Session(const ConnectionProfile& profile,const std::atomic_bool* cancellation):transport{&profile,cancellation,{}}{Initialize();RequireNotCancelled(cancellation);bson_error_t error{};const auto text=profile.url.empty()?"mongodb://"+(profile.host.find(':')==std::string::npos?profile.host:"["+profile.host+"]")+":"+std::to_string(profile.port)+"/":profile.url;uri.value=mongoc_uri_new_with_error(text.c_str(),&error);if(!uri.value)throw std::runtime_error(error.message);if(profile.url.empty())mongoc_uri_set_option_as_bool(uri.value,"tls",profile.sslMode!="disable");if(!profile.username.empty()&&!mongoc_uri_set_username(uri.value,profile.username.c_str()))throw std::runtime_error("Mongo username is invalid.");if(!profile.password.empty()&&!mongoc_uri_set_password(uri.value,profile.password.c_str()))throw std::runtime_error("Mongo password is invalid.");
  const auto options=json::parse(profile.optionsJson);for(auto option=options.begin();option!=options.end();++option){std::string key=option.key();std::transform(key.begin(),key.end(),key.begin(),[](unsigned char c){return static_cast<char>(tolower(c));});if(key=="tlsinsecure"||key=="tlsallowinvalidcertificates"||key=="tlsallowinvalidhostnames"){if(option.value()!=false)throw std::runtime_error("TLS certificate and host-name verification cannot be disabled; select TLS disable only for a plaintext server.");continue;}bool valid=false;if(option.value().is_boolean())valid=mongoc_uri_set_option_as_bool(uri.value,option.key().c_str(),option.value().get<bool>());else if(option.value().is_number_integer())valid=mongoc_uri_set_option_as_int64(uri.value,option.key().c_str(),option.value().get<int64_t>());else if(option.value().is_string())valid=mongoc_uri_set_option_as_utf8(uri.value,option.key().c_str(),option.value().get_ref<const std::string&>().c_str());if(!valid)throw std::runtime_error("Unknown or unsupported native Mongo option: "+option.key());}
  mongoc_uri_set_option_as_int32(uri.value,"connectTimeoutMS",profile.timeoutSec*1000);mongoc_uri_set_option_as_int32(uri.value,"socketTimeoutMS",profile.timeoutSec*1000);mongoc_uri_set_option_as_int32(uri.value,"serverSelectionTimeoutMS",profile.timeoutSec*1000);mongoc_uri_set_option_as_bool(uri.value,"serverSelectionTryOnce",true);
  if(mongoc_uri_get_option_as_bool(uri.value,"tlsInsecure",false)||mongoc_uri_get_option_as_bool(uri.value,"tlsAllowInvalidCertificates",false)||mongoc_uri_get_option_as_bool(uri.value,"tlsAllowInvalidHostnames",false))throw std::runtime_error("The Mongo URL disables TLS verification. Remove its insecure TLS options.");database=profile.database.empty()?(mongoc_uri_get_database(uri.value)?mongoc_uri_get_database(uri.value):""):profile.database;if(database.empty())throw std::runtime_error("Specify the Mongo database name in the profile or URL.");client=mongoc_client_new_from_uri_with_error(uri.value,&error);if(!client)throw std::runtime_error(error.message);mongoc_client_set_error_api(client,2);mongoc_client_set_stream_initiator(client,Initiate,&transport);
 }
 ~Session(){if(client)mongoc_client_destroy(client);}
 void Check(bool valid,const bson_error_t& error){RequireNotCancelled(transport.cancellation);if(!valid)throw std::runtime_error(transport.error.empty()?error.message:transport.error);}
};
struct Collection {mongoc_collection_t* value=nullptr;Collection(Session& session,const std::string& name){if(name.empty()||name.find('\0')!=std::string::npos)throw std::runtime_error("Specify a valid collection name.");value=mongoc_client_get_collection(session.client,session.database.c_str(),name.c_str());if(!value)throw std::runtime_error("Cannot open the Mongo collection.");}~Collection(){if(value)mongoc_collection_destroy(value);} };
struct Cursor {mongoc_cursor_t* value;explicit Cursor(mongoc_cursor_t* cursor):value(cursor){if(!cursor)throw std::runtime_error("Mongo cursor could not be created.");}~Cursor(){mongoc_cursor_destroy(value);} };
std::vector<json> Fetch(Session& session,mongoc_cursor_t* cursor,size_t limit){Cursor owner(cursor);std::vector<json> rows;const bson_t* document=nullptr;while(mongoc_cursor_next(cursor,&document)){RequireNotCancelled(session.transport.cancellation);rows.push_back(Document(document));if(rows.size()>=limit)break;}bson_error_t error{};session.Check(!mongoc_cursor_error(cursor,&error),error);return rows;}
std::vector<std::string> Names(Session& session){auto db=mongoc_client_get_database(session.client,session.database.c_str());Bson opts({{"nameOnly",true}});auto cursor=mongoc_database_find_collections_with_opts(db,opts.value);mongoc_database_destroy(db);auto rows=Fetch(session,cursor,10001);if(rows.size()>10000)throw std::runtime_error("Mongo schema exceeds 10,000 collections.");std::vector<std::string> names;for(const auto& row:rows)names.push_back(row.at("name").get<std::string>());std::sort(names.begin(),names.end());return names;}
std::vector<ColumnMeta> Columns(const std::vector<json>& rows){std::map<std::string,ColumnMeta> found;std::vector<std::string> order;for(const auto& row:rows)for(auto value=row.begin();value!=row.end();++value){if(!found.count(value.key())){ColumnMeta column;column.name=value.key();column.type="TEXT";column.pk=column.name=="_id";column.notnull=column.pk;found[column.name]=column;order.push_back(column.name);}if(value.value().is_structured())found[value.key()].type="JSON";}std::vector<ColumnMeta> columns;for(const auto& name:order)columns.push_back(found.at(name));if(columns.empty()){ColumnMeta id;id.name="_id";id.type="ObjectId";id.pk=id.notnull=true;columns.push_back(id);}return columns;}
json RowJson(const TypedRow& row){json result=json::object();for(const auto& item:row)result[item.first]=DbValueJson(item.second);return result;}
void AppendRows(QueryResult& result,const std::vector<json>& rows,size_t maximum){const auto columns=Columns(rows);for(const auto& column:columns)result.columns.push_back(column.name);result.truncated=rows.size()>maximum;for(size_t i=0;i<std::min(rows.size(),maximum);++i){TypedRow typed;std::map<std::string,std::string> display;for(const auto& column:result.columns){auto value=DbValueFromJson(rows[i].contains(column)?rows[i].at(column):json());display[column]=DbValueDisplay(value);typed[column]=std::move(value);}result.typedRows.push_back(std::move(typed));result.rows.push_back(std::move(display));}result.rowCount=static_cast<int64_t>(result.rows.size());QueryResultSet set;set.query=result.query;set.columns=result.columns;set.rows=result.rows;set.typedRows=result.typedRows;set.rowCount=result.rowCount;set.rowsAffected=result.rowsAffected;set.truncated=result.truncated;result.resultSets.push_back(std::move(set));}
bool PipelineWrites(const json& value){if(value.is_object()){for(auto i=value.begin();i!=value.end();++i)if(i.key()=="$out"||i.key()=="$merge"||PipelineWrites(i.value()))return true;}else if(value.is_array()){for(const auto& item:value)if(PipelineWrites(item))return true;}return false;}
json SearchPredicate(Session& session,Collection& collection,const std::string& search,const std::string& column={},const std::string& filter={}){
 auto escape=[](const std::string& value){std::string text;for(char c:value){if(std::string(".*+?^$()[]{}|\\").find(c)!=std::string::npos)text+='\\';text+=c;}return text;};
 if(!column.empty())return {{column,{{"$regex",escape(filter)},{"$options","i"}}}};
 if(search.empty())return json::object();
 Bson none,opts({{"limit",20},{"maxTimeMS",session.transport.profile->timeoutSec*1000}});const auto fields=Columns(Fetch(session,mongoc_collection_find_with_opts(collection.value,none.value,opts.value,nullptr),20));json ors=json::array();
 for(const auto& field:fields)if(field.name!="_id")ors.push_back({{field.name,{{"$regex",escape(search)},{"$options","i"}}}});
 return ors.empty()?json{{"_id",nullptr}}:json{{"$or",ors}};
}
class MongoProvider final:public DatabaseProvider {
public:using DatabaseProvider::DatabaseProvider;
 void Test(const std::atomic_bool* cancellation)override{Session session(profile_,cancellation);Bson ping({{"ping",1}});bson_error_t error{};session.Check(mongoc_client_command_simple(session.client,"admin",ping.value,nullptr,nullptr,&error),error);}
 QueryResult Query(const std::string& text,int rows,const std::atomic_bool* cancellation)override{return Execute(json::parse(text),text,std::clamp(rows,1,10000),cancellation);}
 DatabaseSchema Schema(const std::atomic_bool* cancellation)override{Session session(profile_,cancellation);DatabaseSchema result;result.databaseId=profile_.id;result.databaseName=profile_.name;result.kind="document";result.dialect="mongodb";result.capabilities=ProviderCapabilities(result.kind,profile_.readOnly,result.dialect);for(const auto& name:Names(session)){Collection collection(session,name);Bson filter,opts({{"limit",20},{"maxTimeMS",profile_.timeoutSec*1000}});auto samples=Fetch(session,mongoc_collection_find_with_opts(collection.value,filter.value,opts.value,nullptr),20);TableMeta table;table.name=name;table.type="collection";table.editable=!profile_.readOnly;table.primaryKeys={"_id"};table.columns=Columns(samples);bson_error_t error{};table.rowCount=mongoc_collection_count_documents(collection.value,filter.value,nullptr,nullptr,nullptr,&error);session.Check(table.rowCount>=0,error);auto indexes=Fetch(session,mongoc_collection_find_indexes_with_opts(collection.value,nullptr),10000);for(const auto& index:indexes){IndexMeta item;item.name=index.value("name","");item.unique=index.value("unique",false);if(index.contains("key"))for(auto field=index.at("key").begin();field!=index.at("key").end();++field)item.columns.push_back(field.key());table.indexes.push_back(item);}result.tables.push_back(std::move(table));}return result;}
 TableDataResult Table(const std::string& name,int page,int pageSize,const std::string& sort,const std::string& direction,const std::string& search,const std::string& column,const std::string& filter,const std::atomic_bool* cancellation)override{TableDataResult result;result.table=name;try{Session session(profile_,cancellation);Existing(session,name);Collection collection(session,name);const auto predicate=SearchPredicate(session,collection,search,column,filter);
  Bson query(predicate);bson_error_t error{};result.totalRows=mongoc_collection_count_documents(collection.value,query.value,nullptr,nullptr,nullptr,&error);session.Check(result.totalRows>=0,error);result.pageSize=std::clamp(pageSize,1,200);result.totalPages=static_cast<int>(std::min<int64_t>(INT_MAX,std::max<int64_t>(1,(result.totalRows+result.pageSize-1)/result.pageSize)));result.page=std::clamp(page,1,result.totalPages);const auto request=json{{"collection",name},{"filter",predicate},{"operation","find"},{"skip",static_cast<int64_t>(result.page-1)*result.pageSize},{"limit",result.pageSize},{"sort",{{sort.empty()?"_id":sort,_stricmp(direction.c_str(),"desc")==0?-1:1}}}};auto rows=Execute(request,request.dump(),result.pageSize,cancellation);if(!rows.error.empty())throw std::runtime_error(rows.error);result.columns=rows.columns;result.rows=std::move(rows.rows);result.typedRows=std::move(rows.typedRows);for(const auto& field:result.columns){ColumnMeta meta;meta.name=field;meta.type="JSON";meta.pk=meta.notnull=field=="_id";result.columnMetadata.push_back(meta);}result.primaryKeys={"_id"};}
  catch(const std::exception& error){result.error=ScrubConnectionError(error.what(),profile_);result.rows.clear();result.typedRows.clear();}return result;}
 bool Insert(const std::string& name,const TypedRow& values,const std::atomic_bool* cancellation)override{Writable();Session session(profile_,cancellation);Existing(session,name);auto result=Execute({{"collection",name},{"operation","insert_one"},{"document",RowJson(values)}},"",1,cancellation);if(!result.error.empty())throw std::runtime_error(result.error);return result.rowsAffected==1;}
 bool Update(const std::string& name,const TypedRow& key,const TypedRow& values,const std::atomic_bool* cancellation)override{Writable();Key(key);Session session(profile_,cancellation);Existing(session,name);json fields=RowJson(values);if(fields.contains("_id")){if(fields["_id"]!=DbValueJson(key.at("_id")))throw std::runtime_error("A document's _id cannot be changed.");fields.erase("_id");}if(fields.empty())throw std::runtime_error("Provide nonempty document fields.");auto result=Execute({{"collection",name},{"operation","update_one"},{"filter",RowJson(key)},{"update",{{"$set",fields}}}},"",1,cancellation);if(!result.error.empty())throw std::runtime_error(result.error);return !result.rows.empty()&&result.rows[0].at("matched")!="0";}
 bool Delete(const std::string& name,const TypedRow& key,const std::atomic_bool* cancellation)override{Writable();Key(key);Session session(profile_,cancellation);Existing(session,name);auto result=Execute({{"collection",name},{"operation","delete_one"},{"filter",RowJson(key)}},"",1,cancellation);if(!result.error.empty())throw std::runtime_error(result.error);return result.rowsAffected==1;}
 std::string Export(const std::string& name,const std::string& format,const std::string& search,const std::string& sort,const std::string& direction,const std::atomic_bool* cancellation)override{if(format=="sql")throw std::runtime_error("Mongo exports support JSON and CSV.");Session session(profile_,cancellation);Existing(session,name);Collection collection(session,name);const auto predicate=SearchPredicate(session,collection,search);auto result=Execute({{"collection",name},{"operation","find"},{"filter",predicate},{"limit",100000},{"sort",{{sort.empty()?"_id":sort,_stricmp(direction.c_str(),"desc")==0?-1:1}}}},"",100000,cancellation);if(!result.error.empty())throw std::runtime_error(result.error);if(result.truncated)throw std::runtime_error("Mongo exports are limited to 100,000 documents; narrow the search.");RequireNotCancelled(cancellation);return ExportTypedRows(result.columns,result.typedRows,format);}
private:
 void Writable()const{if(profile_.readOnly)throw std::runtime_error("This connection is read-only.");}
 static void Key(const TypedRow& key){if(key.size()!=1||!key.count("_id")||key.at("_id").type==DbValueType::Null)throw std::runtime_error("Provide the _id primary key to identify one document.");}
 static void Existing(Session& session,const std::string& name){const auto names=Names(session);if(std::find(names.begin(),names.end(),name)==names.end())throw std::runtime_error("Collection not found; create it with a native insert query.");}
 QueryResult Execute(const json& command,const std::string& text,int maximum,const std::atomic_bool* cancellation){QueryResult result;result.query=text;const auto started=std::chrono::steady_clock::now();try{if(!command.is_object()||!command.contains("collection")||!command["collection"].is_string()||command["collection"].get<std::string>().empty())throw std::runtime_error("Specify a collection name in a Mongo JSON query object.");const auto operation=command.value("operation","find");static const std::set<std::string> reads={"find","find_one","count","distinct","aggregate"};if(profile_.readOnly&&(!reads.count(operation)||PipelineWrites(command.value("pipeline",json::array()))))throw std::runtime_error("This connection is read-only.");const auto limit=std::clamp(command.value("limit",maximum),1,maximum);Session session(profile_,cancellation);Collection collection(session,command.at("collection").get<std::string>());Bson filter(command.value("filter",json::object()));bson_error_t error{};std::vector<json> rows;
   if(operation=="find"||operation=="find_one"){json options={{"limit",operation=="find_one"?1:limit+1},{"skip",std::max<int64_t>(0,command.value("skip",int64_t{0}))},{"maxTimeMS",profile_.timeoutSec*1000}};if(command.contains("sort"))options["sort"]=command["sort"];if(command.contains("projection"))options["projection"]=command["projection"];Bson opts(options);rows=Fetch(session,mongoc_collection_find_with_opts(collection.value,filter.value,opts.value,nullptr),static_cast<size_t>(limit+1));}
   else if(operation=="aggregate"){auto pipeline=command.value("pipeline",json::array());if(!pipeline.is_array())throw std::runtime_error("Mongo pipeline must be an array.");pipeline.push_back({{"$limit",limit+1}});Bson stages({{"pipeline",pipeline}}),opts({{"maxTimeMS",profile_.timeoutSec*1000}});rows=Fetch(session,mongoc_collection_aggregate(collection.value,MONGOC_QUERY_NONE,stages.value,opts.value,nullptr),static_cast<size_t>(limit+1));}
   else if(operation=="count"){const auto count=mongoc_collection_count_documents(collection.value,filter.value,nullptr,nullptr,nullptr,&error);session.Check(count>=0,error);rows={{{"count",count}}};}
   else if(operation=="distinct"){Bson query({{"distinct",command.at("collection")},{"key",command.at("field")},{"query",command.value("filter",json::object())},{"maxTimeMS",profile_.timeoutSec*1000}});bson_t reply=BSON_INITIALIZER;const auto valid=mongoc_client_command_simple(session.client,session.database.c_str(),query.value,nullptr,&reply,&error);json document=Document(&reply);bson_destroy(&reply);session.Check(valid,error);for(const auto& value:document.at("values")){rows.push_back({{"value",value}});if(rows.size()>static_cast<size_t>(limit))break;}}
   else if(operation=="insert_one"){json document=command.value("document",json::object());if(!document.is_object())throw std::runtime_error("Mongo document must be an object.");if(!document.contains("_id")){bson_oid_t id{};bson_oid_init(&id,nullptr);char textId[25]{};bson_oid_to_string(&id,textId);document["_id"]={{"$oid",textId}};}Bson input(document);bson_t reply=BSON_INITIALIZER;const auto valid=mongoc_collection_insert_one(collection.value,input.value,nullptr,&reply,&error);bson_destroy(&reply);session.Check(valid,error);rows={{{"inserted_id",document["_id"]}}};result.rowsAffected=1;}
   else if(operation=="update_one"||operation=="delete_one"){bson_t reply=BSON_INITIALIZER;bool valid=false;if(operation=="delete_one")valid=mongoc_collection_delete_one(collection.value,filter.value,nullptr,&reply,&error);else{Bson update(command.value("update",json::object())),opts({{"upsert",command.value("upsert",false)}});valid=mongoc_collection_update_one(collection.value,filter.value,update.value,opts.value,&reply,&error);}const auto document=Document(&reply);bson_destroy(&reply);session.Check(valid,error);if(operation=="delete_one"){result.rowsAffected=document.value("deletedCount",int64_t{0});rows={{{"deleted",result.rowsAffected}}};}else{result.rowsAffected=document.value("modifiedCount",int64_t{0});rows={{{"matched",document.value("matchedCount",int64_t{0})},{"modified",result.rowsAffected}}};}}
   else throw std::runtime_error("Supported Mongo operations: find, find_one, aggregate, count, distinct, insert_one, update_one, delete_one.");RequireNotCancelled(cancellation);AppendRows(result,rows,static_cast<size_t>(limit));
  }catch(const std::exception& error){result.error=ScrubConnectionError(error.what(),profile_);result.rows.clear();result.typedRows.clear();result.columns.clear();result.resultSets.clear();result.rowsAffected=0;result.rowCount=0;}result.executionTimeMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();return result;
 }
};
}
std::shared_ptr<DatabaseProvider> CreateMongoProvider(const ConnectionProfile& profile){return std::make_shared<MongoProvider>(profile);}
}
