#include "NativeSocket.h"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#define SECURITY_WIN32
#include <security.h>
#include <schannel.h>
#include <wincrypt.h>
#include <vector>
#include <stdexcept>
#include <chrono>
#include <mutex>
#include <algorithm>
#include <filesystem>
#include <fstream>
#pragma comment(lib,"ws2_32.lib")
#pragma comment(lib,"secur32.lib")
#pragma comment(lib,"crypt32.lib")
namespace native_app {
namespace {
std::wstring Wide(const std::string& value){if(value.empty())return {};const auto size=MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,value.data(),static_cast<int>(value.size()),nullptr,0);if(!size)throw std::runtime_error("Connection host is not valid UTF-8.");std::wstring result(size,0);MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,value.data(),static_cast<int>(value.size()),result.data(),size);return result;}
using Clock=std::chrono::steady_clock;
}
void InitializeNativeSockets(){static std::once_flag initialized;std::call_once(initialized,[]{WSADATA data{};if(WSAStartup(MAKEWORD(2,2),&data))throw std::runtime_error("Windows sockets could not be initialized.");});}
struct NativeSocket::State {
 SOCKET socket=INVALID_SOCKET;int timeout=10;std::atomic<const std::atomic_bool*> cancellation{nullptr};CredHandle credential{};CtxtHandle context{};bool hasCredential=false,hasContext=false,tls=false;SecPkgContext_StreamSizes sizes{};std::vector<char> encrypted,plain;
 void Check(Clock::time_point deadline)const{const auto cancel=cancellation.load();if(cancel&&cancel->load())throw std::runtime_error("Query cancelled.");if(Clock::now()>=deadline)throw std::runtime_error("Database network operation timed out.");}
 Clock::time_point Deadline()const{return Clock::now()+std::chrono::seconds(timeout);}
 void Wait(bool writing,Clock::time_point deadline)const{for(;;){Check(deadline);fd_set reads{},writes{},errors{};FD_ZERO(&reads);FD_ZERO(&writes);FD_ZERO(&errors);FD_SET(socket,writing?&writes:&reads);FD_SET(socket,&errors);timeval interval{0,50000};const auto result=select(0,&reads,&writes,&errors,&interval);if(result==SOCKET_ERROR)throw std::runtime_error("Database socket wait failed.");if(result>0){if(FD_ISSET(socket,&errors))throw std::runtime_error("Database connection failed.");return;}}}
 size_t Receive(void* data,size_t capacity,Clock::time_point deadline){for(;;){Wait(false,deadline);const int count=recv(socket,static_cast<char*>(data),static_cast<int>(std::min<size_t>(capacity,INT_MAX)),0);if(count>=0)return static_cast<size_t>(count);if(WSAGetLastError()!=WSAEWOULDBLOCK)throw std::runtime_error("Database connection read failed.");}}
 void Send(const void* data,size_t size,Clock::time_point deadline){size_t written=0;while(written<size){Wait(true,deadline);const int count=send(socket,static_cast<const char*>(data)+written,static_cast<int>(std::min<size_t>(size-written,INT_MAX)),0);if(count>0)written+=count;else if(count==0||WSAGetLastError()!=WSAEWOULDBLOCK)throw std::runtime_error("Database connection write failed.");}}
 void VerifyCustomRoot(const std::string& path,const std::wstring& host){PCCERT_CONTEXT peer=nullptr;if(QueryContextAttributesW(&context,SECPKG_ATTR_REMOTE_CERT_CONTEXT,&peer)!=SEC_E_OK)throw std::runtime_error("TLS did not provide a server certificate.");HCERTSTORE roots=CertOpenStore(CERT_STORE_PROV_MEMORY,0,0,0,nullptr);HCERTCHAINENGINE engine=nullptr;PCCERT_CHAIN_CONTEXT chain=nullptr;
  try{std::ifstream file(std::filesystem::u8path(path),std::ios::binary);if(!file)throw std::runtime_error("Cannot open the configured TLS CA certificate file.");std::string bytes((std::istreambuf_iterator<char>(file)),{});if(bytes.size()>4*1024*1024)throw std::runtime_error("TLS CA certificate file is too large.");bool added=false;size_t start=0;
   for(;;){const auto begin=bytes.find("-----BEGIN CERTIFICATE-----",start);if(begin==std::string::npos)break;const auto end=bytes.find("-----END CERTIFICATE-----",begin);if(end==std::string::npos)throw std::runtime_error("TLS CA PEM certificate is incomplete.");const auto pem=bytes.substr(begin,end+25-begin);DWORD count=0;if(!CryptStringToBinaryA(pem.c_str(),static_cast<DWORD>(pem.size()),CRYPT_STRING_BASE64HEADER,nullptr,&count,nullptr,nullptr))throw std::runtime_error("TLS CA PEM certificate is invalid.");std::vector<BYTE> der(count);if(!CryptStringToBinaryA(pem.c_str(),static_cast<DWORD>(pem.size()),CRYPT_STRING_BASE64HEADER,der.data(),&count,nullptr,nullptr)||!CertAddEncodedCertificateToStore(roots,X509_ASN_ENCODING,der.data(),count,CERT_STORE_ADD_REPLACE_EXISTING,nullptr))throw std::runtime_error("TLS CA certificate cannot be loaded.");added=true;start=end+25;}
   if(!added&&!CertAddEncodedCertificateToStore(roots,X509_ASN_ENCODING,reinterpret_cast<const BYTE*>(bytes.data()),static_cast<DWORD>(bytes.size()),CERT_STORE_ADD_REPLACE_EXISTING,nullptr))throw std::runtime_error("TLS CA file must contain PEM or DER certificates.");
   CERT_CHAIN_ENGINE_CONFIG configuration{};configuration.cbSize=sizeof(configuration);configuration.hExclusiveRoot=roots;if(!CertCreateCertificateChainEngine(&configuration,&engine))throw std::runtime_error("Cannot create the TLS certificate verifier.");CERT_CHAIN_PARA parameters{};parameters.cbSize=sizeof(parameters);LPSTR usages[]={const_cast<char*>(szOID_PKIX_KP_SERVER_AUTH)};parameters.RequestedUsage.dwType=USAGE_MATCH_TYPE_AND;parameters.RequestedUsage.Usage.cUsageIdentifier=1;parameters.RequestedUsage.Usage.rgpszUsageIdentifier=usages;
   if(!CertGetCertificateChain(engine,peer,nullptr,peer->hCertStore,&parameters,0,nullptr,&chain))throw std::runtime_error("Cannot verify the database TLS certificate chain.");SSL_EXTRA_CERT_CHAIN_POLICY_PARA extra{};extra.cbSize=sizeof(extra);extra.dwAuthType=AUTHTYPE_SERVER;extra.pwszServerName=const_cast<wchar_t*>(host.c_str());CERT_CHAIN_POLICY_PARA policy{};policy.cbSize=sizeof(policy);policy.pvExtraPolicyPara=&extra;CERT_CHAIN_POLICY_STATUS status{};status.cbSize=sizeof(status);if(!CertVerifyCertificateChainPolicy(CERT_CHAIN_POLICY_SSL,chain,&policy,&status)||status.dwError)throw std::runtime_error("Database TLS certificate or host name verification failed.");
  }catch(...){if(chain)CertFreeCertificateChain(chain);if(engine)CertFreeCertificateChainEngine(engine);if(roots)CertCloseStore(roots,0);CertFreeCertificateContext(peer);throw;}if(chain)CertFreeCertificateChain(chain);if(engine)CertFreeCertificateChainEngine(engine);CertCloseStore(roots,0);CertFreeCertificateContext(peer);
 }
 void Handshake(const std::string& hostName,const std::string& ca){const auto host=Wide(hostName);SCHANNEL_CRED config{};config.dwVersion=SCHANNEL_CRED_VERSION;config.dwFlags=SCH_CRED_NO_DEFAULT_CREDS|SCH_USE_STRONG_CRYPTO|(ca.empty()?SCH_CRED_AUTO_CRED_VALIDATION:SCH_CRED_MANUAL_CRED_VALIDATION);TimeStamp expiry{};if(AcquireCredentialsHandleW(nullptr,const_cast<wchar_t*>(UNISP_NAME_W),SECPKG_CRED_OUTBOUND,nullptr,&config,nullptr,nullptr,&credential,&expiry)!=SEC_E_OK)throw std::runtime_error("Cannot initialize native Windows TLS credentials.");hasCredential=true;
  const ULONG requested=ISC_REQ_SEQUENCE_DETECT|ISC_REQ_REPLAY_DETECT|ISC_REQ_CONFIDENTIALITY|ISC_REQ_ALLOCATE_MEMORY|ISC_REQ_STREAM;ULONG attributes=0;const auto deadline=Deadline();bool first=true;
  for(;;){Check(deadline);SecBuffer inputBuffers[2]={{static_cast<ULONG>(encrypted.size()),SECBUFFER_TOKEN,encrypted.empty()?nullptr:encrypted.data()},{0,SECBUFFER_EMPTY,nullptr}};SecBufferDesc input{SECBUFFER_VERSION,2,inputBuffers};SecBuffer outputBuffer{0,SECBUFFER_TOKEN,nullptr};SecBufferDesc output{SECBUFFER_VERSION,1,&outputBuffer};const auto status=InitializeSecurityContextW(&credential,first?nullptr:&context,const_cast<wchar_t*>(host.c_str()),requested,0,SECURITY_NATIVE_DREP,first?nullptr:&input,0,&context,&output,&attributes,&expiry);if(status==SEC_E_OK||status==SEC_I_CONTINUE_NEEDED||status==SEC_E_INCOMPLETE_MESSAGE)hasContext=true;
   if(outputBuffer.pvBuffer){try{if(outputBuffer.cbBuffer)Send(outputBuffer.pvBuffer,outputBuffer.cbBuffer,deadline);}catch(...){FreeContextBuffer(outputBuffer.pvBuffer);throw;}FreeContextBuffer(outputBuffer.pvBuffer);}if(status!=SEC_E_OK&&status!=SEC_I_CONTINUE_NEEDED&&status!=SEC_E_INCOMPLETE_MESSAGE)throw std::runtime_error("Database TLS handshake or certificate verification failed.");
   if(!first&&status!=SEC_E_INCOMPLETE_MESSAGE){if(inputBuffers[1].BufferType==SECBUFFER_EXTRA&&inputBuffers[1].cbBuffer<=encrypted.size())encrypted.erase(encrypted.begin(),encrypted.end()-inputBuffers[1].cbBuffer);else encrypted.clear();}first=false;if(status==SEC_E_OK)break;
   char data[16384];const auto count=Receive(data,sizeof(data),deadline);if(!count)throw std::runtime_error("Database closed during TLS handshake.");encrypted.insert(encrypted.end(),data,data+count);if(encrypted.size()>1024*1024)throw std::runtime_error("Database TLS handshake exceeded the message limit.");
  }if(!ca.empty())VerifyCustomRoot(ca,host);if(QueryContextAttributesW(&context,SECPKG_ATTR_STREAM_SIZES,&sizes)!=SEC_E_OK)throw std::runtime_error("Cannot read TLS stream limits.");tls=true;
 }
};
NativeSocket::NativeSocket():state_(std::make_unique<State>()){InitializeNativeSockets();}
NativeSocket::~NativeSocket(){Close();}
void NativeSocket::Close()noexcept{if(!state_)return;if(state_->hasContext){DeleteSecurityContext(&state_->context);state_->hasContext=false;}if(state_->hasCredential){FreeCredentialsHandle(&state_->credential);state_->hasCredential=false;}if(state_->socket!=INVALID_SOCKET){closesocket(state_->socket);state_->socket=INVALID_SOCKET;}state_->tls=false;state_->encrypted.clear();state_->plain.clear();}
void NativeSocket::SetCancellation(const std::atomic_bool* cancellation)noexcept{state_->cancellation.store(cancellation);}
void NativeSocket::SetTimeout(int seconds)noexcept{state_->timeout=std::clamp(seconds,1,60);}
bool NativeSocket::Alive()const noexcept{return state_->socket!=INVALID_SOCKET;}
void NativeSocket::Adopt(std::uintptr_t socket,int timeout,const std::atomic_bool* cancellation){Close();state_->socket=static_cast<SOCKET>(socket);state_->timeout=std::clamp(timeout,1,60);SetCancellation(cancellation);u_long nonblocking=1;if(ioctlsocket(state_->socket,FIONBIO,&nonblocking))throw std::runtime_error("Cannot configure native socket.");}
void NativeSocket::Connect(const std::string& host,unsigned short port,bool tls,const std::string& ca,int timeout,const std::atomic_bool* cancellation){Close();state_->timeout=std::clamp(timeout,1,60);SetCancellation(cancellation);const auto deadline=state_->Deadline();state_->Check(deadline);const auto hostName=Wide(host),service=std::to_wstring(port);ADDRINFOEXW hints{};hints.ai_family=AF_UNSPEC;hints.ai_socktype=SOCK_STREAM;hints.ai_protocol=IPPROTO_TCP;PADDRINFOEXW addresses=nullptr;OVERLAPPED operation{};operation.hEvent=CreateEventW(nullptr,TRUE,FALSE,nullptr);if(!operation.hEvent)throw std::runtime_error("Cannot initialize native DNS lookup.");HANDLE lookup=nullptr;int result=GetAddrInfoExW(hostName.c_str(),service.c_str(),NS_DNS,nullptr,&hints,&addresses,nullptr,&operation,nullptr,&lookup);
 try{if(result==WSA_IO_PENDING){for(;;){state_->Check(deadline);const auto ready=WaitForSingleObject(operation.hEvent,50);if(ready==WAIT_OBJECT_0){result=GetAddrInfoExOverlappedResult(&operation);break;}if(ready==WAIT_FAILED)throw std::runtime_error("Native DNS lookup wait failed.");}}if(result)throw std::runtime_error("Database host name could not be resolved.");}
 catch(...){if(result==WSA_IO_PENDING){GetAddrInfoExCancel(&lookup);WaitForSingleObject(operation.hEvent,INFINITE);}if(addresses)FreeAddrInfoExW(addresses);CloseHandle(operation.hEvent);throw;}CloseHandle(operation.hEvent);
 try{for(auto address=addresses;address;address=address->ai_next){state_->Check(deadline);state_->socket=socket(address->ai_family,address->ai_socktype,address->ai_protocol);if(state_->socket==INVALID_SOCKET)continue;
   bool connected=false;try{u_long nonblocking=1;if(ioctlsocket(state_->socket,FIONBIO,&nonblocking))throw std::runtime_error("Cannot configure native socket.");if(connect(state_->socket,address->ai_addr,static_cast<int>(address->ai_addrlen))==0)connected=true;else if(WSAGetLastError()==WSAEWOULDBLOCK){state_->Wait(true,deadline);int error=0,length=sizeof(error);connected=getsockopt(state_->socket,SOL_SOCKET,SO_ERROR,reinterpret_cast<char*>(&error),&length)==0&&error==0;}}
   catch(...){closesocket(state_->socket);state_->socket=INVALID_SOCKET;state_->Check(deadline);continue;}
   if(connected)break;closesocket(state_->socket);state_->socket=INVALID_SOCKET;
  }if(state_->socket==INVALID_SOCKET)throw std::runtime_error("Database TCP connection could not be established.");FreeAddrInfoExW(addresses);addresses=nullptr;if(tls)state_->Handshake(host,ca);}
 catch(...){if(addresses)FreeAddrInfoExW(addresses);Close();throw;}
}
size_t NativeSocket::Read(void* data,size_t capacity){if(!capacity)return 0;if(!Alive())throw std::runtime_error("Database socket is closed.");const auto deadline=state_->Deadline();if(!state_->tls)return state_->Receive(data,capacity,deadline);
 for(;;){state_->Check(deadline);if(!state_->plain.empty()){const auto count=std::min(capacity,state_->plain.size());memcpy(data,state_->plain.data(),count);state_->plain.erase(state_->plain.begin(),state_->plain.begin()+count);return count;}
  if(!state_->encrypted.empty()){SecBuffer buffers[4]={{static_cast<ULONG>(state_->encrypted.size()),SECBUFFER_DATA,state_->encrypted.data()},{0,SECBUFFER_EMPTY,nullptr},{0,SECBUFFER_EMPTY,nullptr},{0,SECBUFFER_EMPTY,nullptr}};SecBufferDesc descriptor{SECBUFFER_VERSION,4,buffers};const auto status=DecryptMessage(&state_->context,&descriptor,0,nullptr);if(status==SEC_I_CONTEXT_EXPIRED)return 0;if(status==SEC_I_RENEGOTIATE)throw std::runtime_error("Database requested an unsupported TLS renegotiation; reconnect.");if(status!=SEC_E_OK&&status!=SEC_E_INCOMPLETE_MESSAGE)throw std::runtime_error("Database TLS message verification failed.");if(status==SEC_E_OK){ULONG extra=0;for(auto& buffer:buffers){if(buffer.BufferType==SECBUFFER_DATA&&buffer.cbBuffer)state_->plain.insert(state_->plain.end(),static_cast<char*>(buffer.pvBuffer),static_cast<char*>(buffer.pvBuffer)+buffer.cbBuffer);if(buffer.BufferType==SECBUFFER_EXTRA)extra=buffer.cbBuffer;}if(extra&&extra<=state_->encrypted.size())state_->encrypted.erase(state_->encrypted.begin(),state_->encrypted.end()-extra);else state_->encrypted.clear();continue;}}
  char bytes[16384];const auto count=state_->Receive(bytes,sizeof(bytes),deadline);if(!count){if(!state_->encrypted.empty())throw std::runtime_error("Database closed during a TLS record.");return 0;}state_->encrypted.insert(state_->encrypted.end(),bytes,bytes+count);if(state_->encrypted.size()>4*1024*1024)throw std::runtime_error("Database TLS record exceeds the transport limit.");
 }
}
void NativeSocket::Write(const void* data,size_t length){if(!Alive())throw std::runtime_error("Database socket is closed.");const auto deadline=state_->Deadline();if(!state_->tls){state_->Send(data,length,deadline);return;}size_t offset=0;while(offset<length){state_->Check(deadline);const auto size=std::min<size_t>(length-offset,state_->sizes.cbMaximumMessage);std::vector<char> packet(state_->sizes.cbHeader+size+state_->sizes.cbTrailer);memcpy(packet.data()+state_->sizes.cbHeader,static_cast<const char*>(data)+offset,size);SecBuffer buffers[4]={{state_->sizes.cbHeader,SECBUFFER_STREAM_HEADER,packet.data()},{static_cast<ULONG>(size),SECBUFFER_DATA,packet.data()+state_->sizes.cbHeader},{state_->sizes.cbTrailer,SECBUFFER_STREAM_TRAILER,packet.data()+state_->sizes.cbHeader+size},{0,SECBUFFER_EMPTY,nullptr}};SecBufferDesc descriptor{SECBUFFER_VERSION,4,buffers};if(EncryptMessage(&state_->context,0,&descriptor,0)!=SEC_E_OK)throw std::runtime_error("Database TLS encryption failed.");state_->Send(packet.data(),static_cast<size_t>(buffers[0].cbBuffer)+buffers[1].cbBuffer+buffers[2].cbBuffer,deadline);offset+=size;}}
}
