#include "NativeMockServer.h"
#include "NativeSocket.h"
#include "DbEngine.h"
#include "DbValues.h"
#include "VariableResolver.h"
#include <winsock2.h>
#include <ws2tcpip.h>
#include <atomic>
#include <thread>
#include <mutex>
#include <map>
#include <sstream>
#include <algorithm>
#include <stdexcept>
namespace native_app {
namespace {
using json=nlohmann::json;
struct HttpFailure:std::runtime_error{int status;HttpFailure(int code,const std::string& message):std::runtime_error(message),status(code){}};
std::string Lower(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(tolower(c));});return value;}
json JsonRow(const TypedRow& row){json object=json::object();for(const auto& item:row)object[item.first]=DbValueJson(item.second);return object;}
TypedRow Values(const json& object){if(!object.is_object())throw HttpFailure(400,"Request body must be a JSON object.");TypedRow row;for(auto item=object.begin();item!=object.end();++item)row[item.key()]=DbValueFromJson(item.value());return row;}
int Integer(const std::map<std::string,std::string>& params,const std::string& key,int fallback){auto value=params.find(key);if(value==params.end())return fallback;size_t count=0;int result;try{result=std::stoi(value->second,&count);}catch(...){throw HttpFailure(400,"Page and limit must be valid integers.");}if(count!=value->second.size())throw HttpFailure(400,"Page and limit must be valid integers.");return result;}
std::string Parameter(const std::map<std::string,std::string>& params,const std::string& key,const std::string& fallback={}){auto item=params.find(key);return item==params.end()?fallback:item->second;}
std::string Decode(const std::string& text,bool form){for(size_t i=0;i<text.size();++i)if(text[i]=='%'){if(i+2>=text.size()||!isxdigit(static_cast<unsigned char>(text[i+1]))||!isxdigit(static_cast<unsigned char>(text[i+2])))throw HttpFailure(400,"URL contains invalid percent encoding.");i+=2;}auto encoded=text;if(form)std::replace(encoded.begin(),encoded.end(),'+',' ');auto value=VariableResolver::UrlDecode(encoded);if(value.find('\0')!=std::string::npos)throw HttpFailure(400,"URL cannot contain NUL.");return value;}
struct Request {std::string method,target;std::map<std::string,std::string> headers;json body=json::object();};
Request ReadRequest(NativeSocket& client){std::string text;char buffer[8192];size_t end=std::string::npos;while((end=text.find("\r\n\r\n"))==std::string::npos){const auto count=client.Read(buffer,sizeof(buffer));if(!count)throw HttpFailure(400,"Incomplete HTTP request.");text.append(buffer,count);if(text.size()>64*1024)throw HttpFailure(431,"HTTP request headers exceed 64 KiB.");}Request result;std::istringstream lines(text.substr(0,end));std::string line;if(!std::getline(lines,line))throw HttpFailure(400,"Missing HTTP request line.");if(!line.empty()&&line.back()=='\r')line.pop_back();std::istringstream first(line);std::string version,extra;if(!(first>>result.method>>result.target>>version)||(first>>extra)||(version!="HTTP/1.1"&&version!="HTTP/1.0")||result.target.empty()||result.target[0]!='/')throw HttpFailure(400,"Invalid HTTP request line.");
 while(std::getline(lines,line)){if(!line.empty()&&line.back()=='\r')line.pop_back();const auto colon=line.find(':');if(colon==std::string::npos||colon==0||isspace(static_cast<unsigned char>(line[0])))throw HttpFailure(400,"Invalid HTTP request header.");const auto name=Lower(line.substr(0,colon));if(std::any_of(name.begin(),name.end(),[](unsigned char c){return !isalnum(c)&&c!='-';}))throw HttpFailure(400,"Invalid HTTP request header name.");auto value=line.substr(colon+1);const auto start=value.find_first_not_of(" \t"),finish=value.find_last_not_of(" \t");value=start==std::string::npos?"":value.substr(start,finish-start+1);if(result.headers.count(name))throw HttpFailure(400,"Duplicate HTTP request headers are not supported.");result.headers[name]=value;}
 if(result.headers.count("transfer-encoding"))throw HttpFailure(400,"Use Content-Length; chunked request bodies are not supported.");if(result.headers.count("expect"))throw HttpFailure(417,"Expect/continue is not supported by the mock service.");if(result.headers.count("origin")){const auto origin=Lower(result.headers.at("origin"));auto loopback=[&](const std::string& host){const auto base="http://"+host;return origin==base||(origin.rfind(base+":",0)==0&&origin.find_first_not_of("0123456789",base.size()+1)==std::string::npos);};if(!loopback("localhost")&&!loopback("127.0.0.1")&&!loopback("[::1]"))throw HttpFailure(403,"Browser origins must be on loopback to use this local mock service.");}
 size_t length=0;if(result.headers.count("content-length")){const auto value=result.headers.at("content-length");if(value.empty()||std::any_of(value.begin(),value.end(),[](unsigned char c){return !isdigit(c);}))throw HttpFailure(400,"Content-Length must be a nonnegative integer.");try{length=static_cast<size_t>(std::stoull(value));}catch(...){throw HttpFailure(413,"Request body is too large.");}if(length>16*1024*1024)throw HttpFailure(413,"JSON request body exceeds 16 MiB.");}const auto start=end+4;while(text.size()-start<length){const auto count=client.Read(buffer,sizeof(buffer));if(!count)throw HttpFailure(400,"Incomplete HTTP request body.");text.append(buffer,count);}if(length){try{result.body=json::parse(text.substr(start,length));}catch(...){throw HttpFailure(400,"Request body is not valid JSON.");}}
 return result;
}
void Send(NativeSocket& client,int status,const json& document,const std::string& origin={}){const auto body=document.dump();const char* reason=status==200?"OK":status==201?"Created":status==204?"No Content":status==400?"Bad Request":status==403?"Forbidden":status==404?"Not Found":status==405?"Method Not Allowed":status==413?"Content Too Large":status==417?"Expectation Failed":status==431?"Request Header Fields Too Large":"Internal Server Error";std::string headers="HTTP/1.1 "+std::to_string(status)+" "+reason+"\r\nContent-Type: application/json; charset=utf-8\r\nContent-Length: "+std::to_string(body.size())+"\r\nConnection: close\r\nCache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\n";if(!origin.empty()&&origin.find_first_of("\r\n")==std::string::npos)headers+="Access-Control-Allow-Origin: "+origin+"\r\nVary: Origin\r\nAccess-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS\r\nAccess-Control-Allow-Headers: Content-Type\r\n";headers+="\r\n";client.Write(headers.data(),headers.size());client.Write(body.data(),body.size());}
}
struct NativeMockServer::State {
 DbEngine* db;std::atomic_bool stop{false},running{false};std::atomic<unsigned short> port{0};std::thread worker;std::mutex lifecycle;
 explicit State(DbEngine* engine):db(engine){if(!engine)throw std::runtime_error("Mock service requires a database engine.");}
 std::pair<int,json> Route(const Request& request){if(request.method=="OPTIONS")return {200,json::object()};const auto query=request.target.find('?');const auto path=request.target.substr(0,query);std::map<std::string,std::string> params;if(query!=std::string::npos){size_t offset=query+1;while(offset<request.target.size()){const auto end=request.target.find('&',offset),equal=request.target.find('=',offset);const auto finish=end==std::string::npos?request.target.size():end;const auto split=equal!=std::string::npos&&equal<finish?equal:finish;params[Decode(request.target.substr(offset,split-offset),true)]=split<finish?Decode(request.target.substr(split+1,finish-split-1),true):"";offset=finish+1;}}
  static const std::string prefix="/api/mock/data/";if(path.rfind(prefix,0)!=0)throw HttpFailure(404,"Unknown mock API route.");const auto remainder=path.substr(prefix.size());const auto slash=remainder.find('/');const auto table=Decode(remainder.substr(0,slash),false);if(table.empty())throw HttpFailure(400,"Specify a table.");const bool record=slash!=std::string::npos;const auto id=record?Decode(remainder.substr(slash+1),false):"";if(record&&(id.empty()||remainder.find('/',slash+1)!=std::string::npos))throw HttpFailure(400,"Specify one record id.");const auto dbId=Parameter(params,"db","ecommerce");const auto schema=db->GetSchema(dbId,&stop);if(schema.kind!="sql")throw HttpFailure(400,"The mock REST service exposes SQL databases; use provider-native queries for document and key/value databases.");const auto found=std::find_if(schema.tables.begin(),schema.tables.end(),[&](const auto& item){return item.name==table;});if(found==schema.tables.end())throw HttpFailure(404,"Table not found.");TypedRow key;if(record){if(found->primaryKeys.size()!=1)throw HttpFailure(400,"Record endpoints require a single-column primary key; use the grid or SQL console for this table.");key[found->primaryKeys[0]]={DbValueType::Text,id};}
  if(request.method=="GET"){if(record){const auto row=db->FindTypedRow(dbId,table,key,&stop);if(row.empty())throw HttpFailure(404,"Record not found.");return {200,{{"success",true},{"table",table},{"id",id},{"data",JsonRow(row)}}};}const auto data=db->GetTableData(dbId,table,Integer(params,"page",1),Integer(params,"limit",Integer(params,"page_size",25)),Parameter(params,"sort"),Parameter(params,"order",Parameter(params,"sort_dir","asc")),Parameter(params,"search"),"","",&stop);if(!data.error.empty())throw HttpFailure(400,data.error);json rows=json::array();for(const auto& row:data.typedRows)rows.push_back(JsonRow(row));return {200,{{"table",table},{"database",dbId},{"total",data.totalRows},{"page",data.page},{"page_size",data.pageSize},{"total_pages",data.totalPages},{"rows",rows}}};}
  if(request.method=="POST"&&!record){const auto result=db->InsertTypedReturningRow(dbId,table,Values(request.body),&stop);json inserted=nullptr;if(result.returned.size()==1)inserted=DbValueJson(result.returned.begin()->second);return {201,{{"success",result.success},{"last_row_id",inserted},{"rows_affected",result.rowsAffected},{"message","Record inserted into '"+table+"'"},{"table",table},{"database",dbId},{"data",request.body}}};}
  if((request.method=="PUT"||request.method=="PATCH")&&record){const bool changed=db->UpdateTypedRow(dbId,table,key,Values(request.body),&stop);return {changed?200:404,{{"success",changed},{"rows_affected",changed?1:0},{"table",table},{"id",id},{"data",request.body}}};}
  if(request.method=="DELETE"&&record){const bool changed=db->DeleteTypedRow(dbId,table,key,&stop);return {changed?200:404,{{"success",changed},{"rows_affected",changed?1:0},{"table",table},{"id",id}}};}throw HttpFailure(405,"Use GET/POST for tables and GET/PUT/PATCH/DELETE for records.");
 }
 void Run(SOCKET listener){running=true;while(!stop){fd_set reads{};FD_ZERO(&reads);FD_SET(listener,&reads);timeval interval{0,50000};const auto available=select(0,&reads,nullptr,nullptr,&interval);if(available==SOCKET_ERROR)break;if(!available)continue;const auto accepted=accept(listener,nullptr,nullptr);if(accepted==INVALID_SOCKET)continue;try{NativeSocket client;client.Adopt(static_cast<uintptr_t>(accepted),5,&stop);try{const auto request=ReadRequest(client);const auto result=Route(request);Send(client,result.first,result.second,request.headers.count("origin")?request.headers.at("origin"):"");}catch(const HttpFailure& error){Send(client,error.status,{{"success",false},{"error",error.what()}});}catch(const std::exception& error){if(!stop)Send(client,400,{{"success",false},{"error",error.what()}});}}catch(...){}}closesocket(listener);running=false;port=0;}
};
NativeMockServer::NativeMockServer(DbEngine* engine):state_(std::make_unique<State>(engine)){}
NativeMockServer::~NativeMockServer(){Stop();}
unsigned short NativeMockServer::Start(unsigned short port){std::lock_guard<std::mutex> lock(state_->lifecycle);if(state_->worker.joinable()){if(state_->running)return state_->port;state_->worker.join();}InitializeNativeSockets();SOCKET listener=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);if(listener==INVALID_SOCKET)throw std::runtime_error("Cannot create the mock service socket.");BOOL exclusive=TRUE;setsockopt(listener,SOL_SOCKET,SO_EXCLUSIVEADDRUSE,reinterpret_cast<const char*>(&exclusive),sizeof(exclusive));sockaddr_in address{};address.sin_family=AF_INET;address.sin_addr.s_addr=htonl(INADDR_LOOPBACK);address.sin_port=htons(port);if(bind(listener,reinterpret_cast<sockaddr*>(&address),sizeof(address))==SOCKET_ERROR||listen(listener,16)==SOCKET_ERROR){closesocket(listener);throw std::runtime_error("Cannot start the loopback mock service. Select an available port.");}int size=sizeof(address);if(getsockname(listener,reinterpret_cast<sockaddr*>(&address),&size)){closesocket(listener);throw std::runtime_error("Cannot read the mock service port.");}state_->stop=false;state_->port=ntohs(address.sin_port);state_->running=true;try{state_->worker=std::thread([state=state_.get(),listener]{state->Run(listener);});}catch(...){state_->running=false;state_->port=0;closesocket(listener);throw;}return state_->port;}
void NativeMockServer::Stop()noexcept{std::lock_guard<std::mutex> lock(state_->lifecycle);state_->stop=true;if(state_->worker.joinable())state_->worker.join();state_->running=false;state_->port=0;}
bool NativeMockServer::IsRunning()const noexcept{return state_->running.load();}
unsigned short NativeMockServer::Port()const noexcept{return state_->port.load();}
}
