#include "NativeConnections.h"
#include "NativeSocket.h"
#include "DbValues.h"
#include "VariableResolver.h"
#include <windows.h>
#include <regex>
#include <set>
#include <chrono>
namespace native_app {
namespace {
using json=nlohmann::json;
std::string Upper(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(toupper(c));});return value;}
json Bytes(const std::string& value){if(value.empty()||MultiByteToWideChar(CP_UTF8,MB_ERR_INVALID_CHARS,value.data(),static_cast<int>(value.size()),nullptr,0))return value;return {{"$binary",BlobHex(value)},{"$encoding","hex"}};}
class RedisSession {
 NativeSocket socket_;std::string buffered_;size_t responseBytes_=0,responseItems_=0;
 std::string Line(){for(;;){const auto end=buffered_.find("\r\n");if(end!=std::string::npos){const auto result=buffered_.substr(0,end);buffered_.erase(0,end+2);return result;}if(buffered_.size()>1024*1024)throw std::runtime_error("Redis response line exceeds 1 MiB.");Fill();}}
 void Fill(){char bytes[8192];const auto count=socket_.Read(bytes,sizeof(bytes));if(!count)throw std::runtime_error("Redis closed the connection.");responseBytes_+=count;if(responseBytes_>64*1024*1024)throw std::runtime_error("Redis response exceeds 64 MiB; use a narrower command.");buffered_.append(bytes,count);}
 json Read(int depth=0){if(depth>64)throw std::runtime_error("Redis response nesting is too deep.");if(++responseItems_>1000000)throw std::runtime_error("Redis response exceeds one million values; use a narrower command.");const auto line=Line();if(line.empty())throw std::runtime_error("Redis sent an empty response frame.");const char type=line[0];const auto value=line.substr(1);if(type=='+'||type=='=')return value;if(type=='-')throw std::runtime_error("Redis: "+value);if(type==':')return std::stoll(value);if(type=='_')return nullptr;if(type=='#')return value=="t";if(type==',')return std::stod(value);
  if(type=='$'){const auto length=std::stoll(value);if(length==-1)return nullptr;if(length<0||length>64*1024*1024)throw std::runtime_error("Redis binary response exceeds 64 MiB.");const auto count=static_cast<size_t>(length);while(buffered_.size()<count+2)Fill();if(buffered_.compare(count,2,"\r\n"))throw std::runtime_error("Redis binary response is malformed.");const auto result=Bytes(buffered_.substr(0,count));buffered_.erase(0,count+2);return result;}
  if(type=='*'||type=='~'||type=='>'){const auto count=std::stoll(value);if(count==-1)return nullptr;if(count<0||count>1000000)throw std::runtime_error("Redis array response exceeds the item limit.");json result=json::array();for(int64_t i=0;i<count;++i)result.push_back(Read(depth+1));return result;}
  if(type=='%'){const auto count=std::stoll(value);if(count<0||count>500000)throw std::runtime_error("Redis map response exceeds the item limit.");json result=json::object();for(int64_t i=0;i<count;++i){auto key=Read(depth+1),item=Read(depth+1);result[key.is_string()?key.get<std::string>():key.dump()]=std::move(item);}return result;}throw std::runtime_error("Redis sent an unsupported or malformed RESP frame.");
 }
public:
 RedisSession(const ConnectionProfile& profile,const std::atomic_bool* cancellation){std::string host=profile.host,user=profile.username,password=profile.password,database=profile.database,ca=profile.sslCa,clientName;int port=profile.port,readTimeout=profile.timeoutSec,connectTimeout=profile.timeoutSec;bool tls=profile.sslMode!="disable";
  const auto options=json::parse(profile.optionsJson);for(auto option=options.begin();option!=options.end();++option){if(option.key()=="socket_timeout"||option.key()=="socket_connect_timeout"){if(!option.value().is_number())throw std::runtime_error("Redis socket timeouts must be numbers from 1 to 60 seconds.");const auto seconds=option.value().get<double>();if(!std::isfinite(seconds)||seconds<1||seconds>60)throw std::runtime_error("Redis socket timeouts must be numbers from 1 to 60 seconds.");const auto rounded=static_cast<int>(std::ceil(seconds));if(option.key()=="socket_timeout")readTimeout=rounded;else connectTimeout=rounded;}else if(option.key()=="client_name"){if(!option.value().is_string())throw std::runtime_error("Redis client_name must be a string.");clientName=option.value().get<std::string>();}else if(option.key()=="ssl_ca_certs"){if(!option.value().is_string())throw std::runtime_error("Redis ssl_ca_certs must be a certificate file path.");if(ca.empty())ca=option.value().get<std::string>();}else if(option.key()=="decode_responses"&&option.value()==false){}else throw std::runtime_error("Unsupported native Redis option: "+option.key()+". Use socket_timeout, socket_connect_timeout, client_name, ssl_ca_certs, or the connection profile fields.");}
  if(!profile.url.empty()){std::smatch match;static const std::regex uri(R"(^(redis|rediss)://([^/?#]+)(?:/([^?#]*))?(?:\?([^#]*))?$)");if(!std::regex_match(profile.url,match,uri))throw std::runtime_error("Redis URL must use redis:// or rediss://.");tls=match[1]=="rediss";std::string authority=match[2];const auto at=authority.rfind('@');if(at!=std::string::npos){auto auth=authority.substr(0,at);authority.erase(0,at+1);const auto colon=auth.find(':');if(colon==std::string::npos){password=DecodeConnectionComponent(auth);user.clear();}else{user=DecodeConnectionComponent(auth.substr(0,colon));password=DecodeConnectionComponent(auth.substr(colon+1));}}
   if(!authority.empty()&&authority[0]=='['){const auto close=authority.find(']');if(close==std::string::npos)throw std::runtime_error("Redis IPv6 URL is malformed.");host=authority.substr(1,close-1);if(close+1<authority.size()){if(authority[close+1]!=':')throw std::runtime_error("Redis URL port is malformed.");port=std::stoi(authority.substr(close+2));}}else{const auto colon=authority.rfind(':');host=authority.substr(0,colon);if(colon!=std::string::npos)port=std::stoi(authority.substr(colon+1));}if(match[3].matched)database=DecodeConnectionComponent(match[3]);if(match[4].matched&&!match[4].str().empty())throw std::runtime_error("Use the native Redis profile fields for options; URL query options are not supported.");}
  if(port<1||port>65535)throw std::runtime_error("Redis port must be between 1 and 65535.");socket_.Connect(host,static_cast<unsigned short>(port),tls,ca,connectTimeout,cancellation);socket_.SetTimeout(readTimeout);
  if(!password.empty()){if(user.empty())Command({"AUTH",password});else Command({"AUTH",user,password});}if(!database.empty()){size_t used=0;const int index=std::stoi(database,&used);if(used!=database.size()||index<0)throw std::runtime_error("Redis database must be a nonnegative integer.");Command({"SELECT",std::to_string(index)});}if(!clientName.empty())Command({"CLIENT","SETNAME",clientName});
 }
 json Command(const std::vector<std::string>& tokens){if(tokens.empty())throw std::runtime_error("Enter a Redis command.");std::string wire="*"+std::to_string(tokens.size())+"\r\n";for(const auto& token:tokens)wire+="$"+std::to_string(token.size())+"\r\n"+token+"\r\n";if(wire.size()>64*1024*1024)throw std::runtime_error("Redis command exceeds 64 MiB.");responseBytes_=buffered_.size();responseItems_=0;socket_.Write(wire.data(),wire.size());return Read();}
};
std::vector<std::string> Tokens(const std::string& text){if(text.find_first_not_of(" \t\r\n")==std::string::npos)throw std::runtime_error("Enter a Redis command or command/args JSON object.");if(text[text.find_first_not_of(" \t\r\n")]=='{'){const auto value=json::parse(text);if(!value.is_object()||!value.contains("command")||!value["command"].is_string())throw std::runtime_error("Redis query needs a string command and an args array.");std::vector<std::string> result{value["command"].get<std::string>()};if(value.contains("args")){if(!value["args"].is_array())throw std::runtime_error("Redis args must be an array.");for(const auto& argument:value["args"])result.push_back(argument.is_string()?argument.get<std::string>():argument.dump());}return result;}
 std::vector<std::string> result;std::string token;char quote=0;bool escaped=false,started=false;for(char c:text){if(escaped){token+=c;escaped=false;started=true;continue;}if(c=='\\'&&quote!='\''){escaped=true;started=true;continue;}if(quote){if(c==quote)quote=0;else token+=c;started=true;continue;}if(c=='\''||c=='"'){quote=c;started=true;continue;}if(isspace(static_cast<unsigned char>(c))){if(started){result.push_back(token);token.clear();started=false;}}else{token+=c;started=true;}}if(quote||escaped)throw std::runtime_error("Redis command contains an unfinished quote or escape.");if(started)result.push_back(token);return result;
}
class RedisProvider final:public DatabaseProvider {
public:using DatabaseProvider::DatabaseProvider;
 void Test(const std::atomic_bool* cancellation)override{RedisSession session(profile_,cancellation);session.Command({"PING"});}
 DatabaseSchema Schema(const std::atomic_bool* cancellation)override{RedisSession session(profile_,cancellation);DatabaseSchema result;result.databaseId=profile_.id;result.databaseName=profile_.name;result.kind="keyvalue";result.dialect="redis";result.capabilities=ProviderCapabilities(result.kind,profile_.readOnly,result.dialect);TableMeta table;table.name="keys";table.type="keyspace";table.rowCount=session.Command({"DBSIZE"}).get<int64_t>();table.primaryKeys={"key"};table.editable=!profile_.readOnly;table.columns=Columns();result.tables.push_back(table);return result;}
 QueryResult Query(const std::string& text,int rows,const std::atomic_bool* cancellation)override{QueryResult result;result.query=text;const auto started=std::chrono::steady_clock::now();try{auto tokens=Tokens(text);if(tokens.empty())throw std::runtime_error("Enter a Redis command.");tokens[0]=Upper(tokens[0]);const auto& command=tokens[0];static const std::set<std::string> blocked={"SHUTDOWN","CONFIG","MODULE","DEBUG","MONITOR","SUBSCRIBE","PSUBSCRIBE","SSUBSCRIBE","BLPOP","BRPOP","BRPOPLPUSH","BLMOVE","BZPOPMIN","BZPOPMAX","BLMPOP","BZMPOP","SYNC","PSYNC","REPLICAOF","SLAVEOF"};if(blocked.count(command))throw std::runtime_error("Server administration and blocking subscription commands are not supported by this endpoint.");if((command=="XREAD"||command=="XREADGROUP")&&std::any_of(tokens.begin(),tokens.end(),[](const auto& item){return Upper(item)=="BLOCK";}))throw std::runtime_error("Blocking stream reads are not supported.");
   static const std::set<std::string> reads={"GET","MGET","EXISTS","TYPE","TTL","PTTL","SCAN","HGET","HMGET","HGETALL","HLEN","LRANGE","LLEN","SMEMBERS","SCARD","ZRANGE","ZCARD","XRANGE","XLEN","DBSIZE","INFO","PING"};if(profile_.readOnly&&!reads.count(command))throw std::runtime_error("This connection is read-only.");RedisSession session(profile_,cancellation);const auto value=session.Command(tokens);result.columns={"result"};const auto maximum=std::clamp(rows,1,10000);auto add=[&](const json& item){if(result.rows.size()>=static_cast<size_t>(maximum)){result.truncated=true;return;}auto typed=DbValueFromJson(item);result.rows.push_back({{"result",DbValueDisplay(typed)}});result.typedRows.push_back({{"result",typed}});};if(value.is_array())for(const auto& item:value)add(item);else add(value);result.rowCount=static_cast<int64_t>(result.rows.size());QueryResultSet set;set.query=text;set.columns=result.columns;set.rows=result.rows;set.typedRows=result.typedRows;set.rowCount=result.rowCount;set.truncated=result.truncated;result.resultSets.push_back(std::move(set));RequireNotCancelled(cancellation);
  }catch(const std::exception& error){result.error=ScrubConnectionError(error.what(),profile_);result.columns.clear();result.rows.clear();result.typedRows.clear();result.resultSets.clear();result.rowCount=0;}result.executionTimeMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-started).count();return result;}
 TableDataResult Table(const std::string& name,int page,int pageSize,const std::string& sort,const std::string& direction,const std::string& search,const std::string&,const std::string& filter,const std::atomic_bool* cancellation)override{TableDataResult result;result.table=name;try{Resource(name);RedisSession session(profile_,cancellation);auto keys=Keys(session,search.empty()?filter:search,100000);result.totalRows=static_cast<int64_t>(keys.size());result.pageSize=std::clamp(pageSize,1,200);result.totalPages=static_cast<int>(std::max<int64_t>(1,(result.totalRows+result.pageSize-1)/result.pageSize));result.page=std::clamp(page,1,result.totalPages);const bool descending=_stricmp(direction.c_str(),"desc")==0;if(descending)std::reverse(keys.begin(),keys.end());for(const auto& column:Columns())result.columns.push_back(column.name);result.columnMetadata=Columns();result.primaryKeys={"key"};const size_t start=static_cast<size_t>(result.page-1)*result.pageSize;for(size_t i=start;i<std::min(keys.size(),start+result.pageSize);++i){bool sampled=false;result.typedRows.push_back(Row(session,keys[i],false,&sampled));result.truncated=result.truncated||sampled;}if(!sort.empty()&&sort!="key"){if(std::find(result.columns.begin(),result.columns.end(),sort)==result.columns.end())throw std::runtime_error("Unknown Redis sort column.");std::sort(result.typedRows.begin(),result.typedRows.end(),[&](const auto& a,const auto& b){return descending?DbValueDisplay(a.at(sort))>DbValueDisplay(b.at(sort)):DbValueDisplay(a.at(sort))<DbValueDisplay(b.at(sort));});}for(const auto& typed:result.typedRows){std::map<std::string,std::string> row;for(const auto& item:typed)row[item.first]=DbValueDisplay(item.second);result.rows.push_back(row);}}
  catch(const std::exception& error){result.error=ScrubConnectionError(error.what(),profile_);result.rows.clear();result.typedRows.clear();}return result;}
 bool Insert(const std::string& name,const TypedRow& values,const std::atomic_bool* cancellation)override{Resource(name);Writable();const auto key=Key({{"key",values.count("key")?values.at("key"):DbValue{DbValueType::Null,""}}});RedisSession session(profile_,cancellation);auto response=session.Command({"SET",key,Scalar(values.count("value")?values.at("value"):DbValue{}),"NX"});if(response.is_null())throw std::runtime_error("Key already exists.");return true;}
 bool Update(const std::string& name,const TypedRow& key,const TypedRow& values,const std::atomic_bool* cancellation)override{Resource(name);Writable();const auto id=Key(key);if(values.count("key")&&(values.at("key").type!=DbValueType::Text||values.at("key").text!=id))throw std::runtime_error("Use RENAME in the command editor to rename a key.");for(const auto& value:values)if(value.first!="key"&&value.first!="value")throw std::runtime_error("Redis type and TTL are server metadata. Use native commands such as EXPIRE to change expiration.");if(!values.count("value"))throw std::runtime_error("Provide a value edit; the existing Redis value was preserved.");RedisSession session(profile_,cancellation);if(session.Command({"TYPE",id})!="string")throw std::runtime_error("Use a native command to edit non-string Redis values.");return !session.Command({"SET",id,Scalar(values.at("value")),"XX","KEEPTTL"}).is_null();}
 bool Delete(const std::string& name,const TypedRow& key,const std::atomic_bool* cancellation)override{Resource(name);Writable();RedisSession session(profile_,cancellation);return session.Command({"DEL",Key(key)}).get<int64_t>()>0;}
 std::string Export(const std::string& name,const std::string& format,const std::string& search,const std::string&,const std::string& direction,const std::atomic_bool* cancellation)override{Resource(name);if(format=="sql")throw std::runtime_error("Redis exports support JSON and CSV.");RedisSession session(profile_,cancellation);auto keys=Keys(session,search,10000);if(_stricmp(direction.c_str(),"desc")==0)std::reverse(keys.begin(),keys.end());std::vector<TypedRow> rows;for(const auto& key:keys)rows.push_back(Row(session,key,true));return ExportTypedRows({"key","type","ttl","value"},rows,format);}
private:
 static std::vector<ColumnMeta> Columns(){std::vector<ColumnMeta> result;for(const auto& name:{"key","type","ttl","value"}){ColumnMeta column;column.name=name;column.type=column.name=="ttl"?"INTEGER":"TEXT";column.pk=column.name=="key";column.notnull=column.pk;result.push_back(column);}return result;}
 static void Resource(const std::string& name){if(name!="keys")throw std::runtime_error("Redis has one keyspace resource named 'keys'.");}
 void Writable()const{if(profile_.readOnly)throw std::runtime_error("This connection is read-only.");}
 static std::string Key(const TypedRow& key){if(key.size()!=1||!key.count("key")||key.at("key").type!=DbValueType::Text||key.at("key").text.empty())throw std::runtime_error("Provide a nonempty string key.");return key.at("key").text;}
 static std::string Scalar(const DbValue& value){if(value.type==DbValueType::Text||value.type==DbValueType::Blob)return value.text;if(value.type==DbValueType::Integer||value.type==DbValueType::Real)return DbValueJson(value).dump();throw std::runtime_error("Use a native command to insert structured Redis values.");}
 static std::vector<std::string> Keys(RedisSession& session,const std::string& search,size_t limit){std::string pattern="*";for(char c:search){if(c=='*'||c=='?'||c=='['||c==']'||c=='\\')pattern+='\\';pattern+=c;}pattern+='*';std::set<std::string> unique;std::string cursor="0";size_t iterations=0;do{const auto reply=session.Command({"SCAN",cursor,"MATCH",pattern,"COUNT","500"});if(!reply.is_array()||reply.size()!=2||!reply[0].is_string()||!reply[1].is_array())throw std::runtime_error("Redis SCAN response is malformed.");cursor=reply[0].get<std::string>();for(const auto& key:reply[1]){if(!key.is_string())throw std::runtime_error("Binary Redis keys cannot be represented by the data grid; use native commands.");unique.insert(key.get<std::string>());if(unique.size()>limit)throw std::runtime_error("Redis key limit exceeded; narrow the search.");}if(++iterations>1000000)throw std::runtime_error("Redis SCAN did not finish within the cursor limit.");}while(cursor!="0");return {unique.begin(),unique.end()};}
 static TypedRow Row(RedisSession& session,const std::string& key,bool full=false,bool* sampled=nullptr){const auto kind=session.Command({"TYPE",key}).get<std::string>();json value;auto mark=[&](bool partial){if(sampled)*sampled=*sampled||partial;};
  if(kind=="string")value=session.Command({"GET",key});
  else if(kind=="hash"){const auto pairs=session.Command({"HGETALL",key});if(!pairs.is_array()||pairs.size()%2)throw std::runtime_error("Redis hash response is malformed.");value=json::object();for(size_t i=0;i<pairs.size();i+=2)value[pairs[i].is_string()?pairs[i].get<std::string>():pairs[i].dump()]=pairs[i+1];}
  else if(kind=="list"){value=session.Command({"LRANGE",key,"0",full?"-1":"99"});if(!full)mark(session.Command({"LLEN",key}).get<int64_t>()>100);}
  else if(kind=="set"){if(full)value=session.Command({"SMEMBERS",key});else{const auto scan=session.Command({"SSCAN",key,"0","COUNT","100"});if(!scan.is_array()||scan.size()!=2||!scan[0].is_string()||!scan[1].is_array())throw std::runtime_error("Redis set scan response is malformed.");value=scan[1];mark(scan[0]!="0"||value.size()>100);if(value.size()>100)value.erase(value.begin()+100,value.end());}}
  else if(kind=="zset"){const auto pairs=session.Command({"ZRANGE",key,"0",full?"-1":"99","WITHSCORES"});if(!pairs.is_array()||pairs.size()%2)throw std::runtime_error("Redis sorted-set response is malformed.");value=json::array();for(size_t i=0;i<pairs.size();i+=2){auto score=pairs[i+1].is_string()?json::parse(pairs[i+1].get<std::string>()):pairs[i+1];value.push_back(json::array({pairs[i],score}));}if(!full)mark(session.Command({"ZCARD",key}).get<int64_t>()>100);}
  else if(kind=="stream"){const auto entries=full?session.Command({"XRANGE",key,"-","+"}):session.Command({"XRANGE",key,"-","+","COUNT","100"});if(!entries.is_array())throw std::runtime_error("Redis stream response is malformed.");value=json::array();for(const auto& entry:entries){if(!entry.is_array()||entry.size()!=2||!entry[1].is_array()||entry[1].size()%2)throw std::runtime_error("Redis stream fields are malformed.");json fields=json::object();for(size_t i=0;i<entry[1].size();i+=2)fields[entry[1][i].is_string()?entry[1][i].get<std::string>():entry[1][i].dump()]=entry[1][i+1];value.push_back(json::array({entry[0],fields}));}if(!full)mark(session.Command({"XLEN",key}).get<int64_t>()>100);}
  return {{"key",{DbValueType::Text,key}},{"type",{DbValueType::Text,kind}},{"ttl",DbValueFromJson(session.Command({"TTL",key}))},{"value",DbValueFromJson(value)}};
 }
};
}
std::shared_ptr<DatabaseProvider> CreateRedisProvider(const ConnectionProfile& profile){return std::make_shared<RedisProvider>(profile);}
}
