#include <winsock2.h>
#include <ws2tcpip.h>
#include <windows.h>
#include "DbEngine.h"
#include "DbValues.h"
#include "NativeConnections.h"
#include "NativeMockServer.h"
#include "NativeSocket.h"
#include "HttpEngine.h"
#include "TempWorkspace.h"
#include <fstream>
#include <thread>
#include <chrono>
#include <mutex>
#include <set>
#include <iostream>
#include <limits>
#include <cstring>
#include <cmath>
using namespace native_app;
namespace native_app {
bool IncludeOdbcCatalog(const std::string& currentCatalog,const std::string& discoveredCatalog);
std::string OdbcViewDefinitionQuery(const std::string& dialect);
std::string OdbcColumnType(const std::map<std::string,std::string>& row,const std::string& dialect);
std::string BuildOdbcSchemaDdl(const TableMeta& table,const std::string& dialect,const std::string& schema,
    const std::vector<std::map<std::string,std::string>>& foreignRows,const std::string& viewDefinition);
}
namespace {
using json=nlohmann::json;namespace fs=std::filesystem;
void Require(bool condition,const char* message){if(!condition)throw std::runtime_error(message);}
std::string Read(const fs::path& path){std::ifstream file(path,std::ios::binary);return {(std::istreambuf_iterator<char>(file)),{}};}
template<class F>void Reject(F action,const char* message){bool refused=false;try{action();}catch(...){refused=true;}Require(refused,message);}
ApiResponse Request(NativeMockServer& server,const std::string& database,const std::string& route,const std::string& method="GET",const json& body=json::object(),const std::string& query={}){ApiRequest request;request.url="http://127.0.0.1:"+std::to_string(server.Port())+"/api/mock/data/"+route+"?db="+database+query;request.method=HttpMethodFromString(method);request.options.timeoutSec=3;request.options.followRedirects=false;if(method!="GET"&&method!="DELETE"){request.body.type=BodyType::Json;request.body.content=body.dump();}return HttpEngine{}.Execute(request);}
class RespFixture {
 SOCKET listener_=INVALID_SOCKET;std::thread worker_;std::atomic_bool stop_{false};unsigned short port_=0;bool complex_=false;std::map<std::string,std::string> values_{{"alpha","first"},{"binary",std::string("\0\xff",2)}};
 static std::string Line(NativeSocket& socket){std::string text;char byte=0;while(text.size()<1024*1024){if(!socket.Read(&byte,1))throw std::runtime_error("Fixture closed.");text+=byte;if(text.size()>1&&text.substr(text.size()-2)=="\r\n"){text.resize(text.size()-2);return text;}}throw std::runtime_error("Fixture line limit.");}
 static std::vector<std::string> Command(NativeSocket& socket){auto header=Line(socket);if(header.empty()||header[0]!='*')throw std::runtime_error("Expected RESP array.");const int count=std::stoi(header.substr(1));std::vector<std::string> tokens;for(int i=0;i<count;++i){const auto frame=Line(socket);if(frame.empty()||frame[0]!='$')throw std::runtime_error("Expected RESP bulk string.");const auto size=static_cast<size_t>(std::stoul(frame.substr(1)));std::string text(size,0);size_t offset=0;while(offset<size){const auto read=socket.Read(text.data()+offset,size-offset);if(!read)throw std::runtime_error("Fixture closed.");offset+=read;}Require(Line(socket).empty(),"RESP bulk terminator invalid");tokens.push_back(text);}return tokens;}
 static std::string Bulk(const std::string& text){return "$"+std::to_string(text.size())+"\r\n"+text+"\r\n";}
 std::string Complex(const std::vector<std::string>& tokens){const auto& command=tokens[0];if(command=="CLIENT"&&tokens.size()==3&&tokens[1]=="SETNAME")return "+OK\r\n";if(!complex_)return {};static const std::map<std::string,std::string> types{{"list-key","list"},{"set-key","set"},{"zset-key","zset"},{"stream-key","stream"}};
  if(command=="DBSIZE")return ":6\r\n";if(command=="SCAN"){std::string result="*2\r\n$1\r\n0\r\n*6\r\n";for(const auto& item:values_)result+=Bulk(item.first);for(const auto& item:types)result+=Bulk(item.first);return result;}if(tokens.size()<2||!types.count(tokens[1]))return {};if(command=="TYPE")return Bulk(types.at(tokens[1]));if(command=="TTL")return ":-1\r\n";if(command=="LLEN"||command=="ZCARD"||command=="XLEN")return ":250\r\n";
  if(command=="LRANGE"||command=="SMEMBERS"||command=="SSCAN"||command=="ZRANGE"||command=="XRANGE"){const int size=command=="SMEMBERS"?250:command=="SSCAN"?100:command=="XRANGE"?(tokens.size()==4?250:100):tokens.at(3)=="-1"?250:100;std::string result=command=="SSCAN"?"*2\r\n$1\r\n7\r\n":"";result+="*"+std::to_string(command=="ZRANGE"?size*2:size)+"\r\n";for(int i=0;i<size;++i){if(command=="XRANGE")result+="*2\r\n"+Bulk(std::to_string(i)+"-0")+"*2\r\n"+Bulk("field")+Bulk("value-"+std::to_string(i));else{result+=Bulk("value-"+std::to_string(i));if(command=="ZRANGE")result+=Bulk(std::to_string(i));}}return result;}return {};
 }
 std::string Execute(const std::vector<std::string>& tokens){if(tokens.empty())return "-missing command\r\n";const auto complex=Complex(tokens);if(!complex.empty())return complex;const auto& command=tokens[0];if(command=="PING")return "+PONG\r\n";if(command=="AUTH"||command=="SELECT")return "+OK\r\n";if(command=="DBSIZE")return ":"+std::to_string(values_.size())+"\r\n";if(command=="SCAN"){std::string response="*2\r\n$1\r\n0\r\n*"+std::to_string(values_.size())+"\r\n";for(const auto& item:values_)response+=Bulk(item.first);return response;}if(command=="TYPE")return Bulk(values_.count(tokens.at(1))?"string":"none");if(command=="TTL")return values_.count(tokens.at(1))?":-1\r\n":":-2\r\n";if(command=="GET"){auto value=values_.find(tokens.at(1));return value==values_.end()?"$-1\r\n":Bulk(value->second);}if(command=="SET"){const bool exists=values_.count(tokens.at(1))!=0;const bool nx=std::find(tokens.begin(),tokens.end(),"NX")!=tokens.end(),xx=std::find(tokens.begin(),tokens.end(),"XX")!=tokens.end();if((nx&&exists)||(xx&&!exists))return "$-1\r\n";values_[tokens.at(1)]=tokens.at(2);return "+OK\r\n";}if(command=="DEL")return values_.erase(tokens.at(1))?":1\r\n":":0\r\n";if(command=="SLOW"){for(int i=0;i<200&&!stop_;++i)Sleep(10);return "+late\r\n";}return "-unsupported fixture command\r\n";}
 void Run(){while(!stop_){fd_set reads;FD_ZERO(&reads);FD_SET(listener_,&reads);timeval timeout{0,50000};if(select(0,&reads,nullptr,nullptr,&timeout)<=0)continue;const auto accepted=accept(listener_,nullptr,nullptr);if(accepted==INVALID_SOCKET)continue;try{NativeSocket socket;socket.Adopt(static_cast<uintptr_t>(accepted),3,&stop_);while(!stop_){const auto tokens=Command(socket);const auto result=Execute(tokens);socket.Write(result.data(),result.size());}}catch(...){}}}
public:
 explicit RespFixture(bool complex=false):complex_(complex){InitializeNativeSockets();listener_=socket(AF_INET,SOCK_STREAM,IPPROTO_TCP);sockaddr_in address{};address.sin_family=AF_INET;address.sin_addr.s_addr=htonl(INADDR_LOOPBACK);Require(listener_!=INVALID_SOCKET&&!bind(listener_,reinterpret_cast<sockaddr*>(&address),sizeof(address))&&!listen(listener_,8),"RESP fixture bind failed");int count=sizeof(address);getsockname(listener_,reinterpret_cast<sockaddr*>(&address),&count);port_=ntohs(address.sin_port);worker_=std::thread([this]{Run();});}
 ~RespFixture(){stop_=true;if(worker_.joinable())worker_.join();closesocket(listener_);}
 unsigned short Port()const{return port_;}
};
}
void TestNativeTypedProfiles(){
 Require(IncludeOdbcNamespace("",""),"Schema-less ODBC metadata was rejected");
 Reject([]{IncludeOdbcNamespace("","public");},"Unqualified ODBC table from a named schema was accepted");
 Require(IncludeOdbcNamespace("public","public")&&IncludeOdbcNamespace("a_b","a_b"),"Explicit ODBC schema was rejected");
 Require(!IncludeOdbcNamespace("a_b","axb")&&!IncludeOdbcNamespace("public","other"),"ODBC schema wildcard matched a different namespace");
 Require(IncludeOdbcCatalog("","")&&IncludeOdbcCatalog("current_database","current_database"),"ODBC schema-less or exact current catalog was rejected");
 Require(!IncludeOdbcCatalog("current_database","other_database")&&!IncludeOdbcCatalog("a_b","axb"),"ODBC discovery accepted a different or wildcard-matched database catalog");
 Reject([]{IncludeOdbcCatalog("","unresolved_database");},"ODBC discovery guessed an unresolved current catalog");
 TableMeta ddlTable;ddlTable.name="child\"table";ddlTable.columns={{0,"id","INTEGER",true,"",true},{1,"parent\"one","INTEGER"},{2,"parent_two","INTEGER"},{3,"label","VARCHAR(42)",false,"'demo'"},{4,"optional","INTEGER",false,"NULL"}};ddlTable.primaryKeys={"id"};
 std::map<std::string,std::string> foreignFirst{{"KEY_SEQ","1"},{"FK_NAME","fk\"pair"},{"FKCOLUMN_NAME","parent\"one"},{"PKTABLE_NAME","parent\"table"},{"PKTABLE_SCHEM","other\"schema"},{"PKCOLUMN_NAME","one"},{"UPDATE_RULE","0"},{"DELETE_RULE","2"}};
 auto foreignSecond=foreignFirst;foreignSecond["KEY_SEQ"]="2";foreignSecond["FKCOLUMN_NAME"]="parent_two";foreignSecond["PKCOLUMN_NAME"]="two";
 const auto ddl=BuildOdbcSchemaDdl(ddlTable,"postgresql","quoted\"schema",{foreignSecond,foreignFirst},"");
 Require(ddl.find("CREATE TABLE \"quoted\"\"schema\".\"child\"\"table\"")!=std::string::npos&&ddl.find("PRIMARY KEY (\"id\")")!=std::string::npos&&ddl.find("DEFAULT 'demo'")!=std::string::npos&&ddl.find("DEFAULT NULL")!=std::string::npos,"ODBC reconstructed DDL lost quoted identifiers, PK, or defaults");
 Require(ddl.find("CONSTRAINT \"fk\"\"pair\" FOREIGN KEY (\"parent\"\"one\", \"parent_two\") REFERENCES \"other\"\"schema\".\"parent\"\"table\" (\"one\", \"two\") ON UPDATE CASCADE ON DELETE SET NULL")!=std::string::npos,"ODBC composite FK reconstruction lost ordering, target namespace, or actions");
 auto view=ddlTable;view.type="view";const std::string definition="SELECT id FROM existing_table";
 Require(BuildOdbcSchemaDdl(view,"postgresql","public",{},definition)==definition,"ODBC replaced a server view definition with fabricated table DDL");
 const auto unavailable=BuildOdbcSchemaDdl(view,"odbc","public",{},"");Require(unavailable.find("View definition unavailable")!=std::string::npos&&unavailable.find("CREATE TABLE")==std::string::npos,"Unavailable ODBC view definition was fabricated");
 auto incomplete=foreignSecond;incomplete["KEY_SEQ"]="3";const auto partial=BuildOdbcSchemaDdl(ddlTable,"postgresql","public",{foreignFirst,incomplete},"");Require(partial.find("FOREIGN KEY (")==std::string::npos&&partial.find("incomplete foreign-key")!=std::string::npos,"Incomplete composite ODBC FK was presented as valid DDL");
 std::map<std::string,std::string> characterType{{"TYPE_NAME","VARCHAR"},{"DATA_TYPE","12"},{"COLUMN_SIZE","42"}};Require(OdbcColumnType(characterType,"mysql")=="VARCHAR(42)","ODBC DDL lost character width");
 std::map<std::string,std::string> decimalType{{"TYPE_NAME","DECIMAL"},{"DATA_TYPE","3"},{"COLUMN_SIZE","38"},{"DECIMAL_DIGITS","9"}};Require(OdbcColumnType(decimalType,"mssql")=="DECIMAL(38,9)","ODBC DDL lost decimal precision/scale");
 characterType["COLUMN_SIZE"]="0";Require(OdbcColumnType(characterType,"mssql")=="VARCHAR(MAX)","ODBC DDL lost SQL Server unlimited character size");
 characterType["TYPE_NAME"]="citext";characterType["COLUMN_SIZE"]="42";Require(OdbcColumnType(characterType,"postgresql")=="citext","ODBC inferred invalid width for a driver-mapped custom type");
 decimalType["TYPE_NAME"]="MONEY";Require(OdbcColumnType(decimalType,"mssql")=="MONEY","ODBC inferred invalid decimal precision for a native money type");
 auto truncatedDefault=ddlTable;truncatedDefault.columns[3].dfltValue="TRUNCATED";const auto safeDefault=BuildOdbcSchemaDdl(truncatedDefault,"postgresql","public",{},"");Require(safeDefault.find("DEFAULT TRUNCATED")==std::string::npos&&safeDefault.find("truncated by the driver")!=std::string::npos,"ODBC presented a truncated default as an executable expression");
 auto bracketed=ddlTable;bracketed.name="order]name";Require(BuildOdbcSchemaDdl(bracketed,"mssql","schema]name",{},"").find("CREATE TABLE [schema]]name].[order]]name]")!=std::string::npos,"ODBC SQL Server DDL lost escaped bracket identifiers");
 for(const auto& dialect:{"postgresql","mysql","mariadb","mssql","oracle","snowflake"}){const auto query=OdbcViewDefinitionQuery(dialect);Require(!query.empty()&&std::count(query.begin(),query.end(),'?')==2&&query.find("quoted")==std::string::npos,"ODBC view lookup did not use bound schema/name parameters");}
 Require(OdbcViewDefinitionQuery("odbc").empty(),"Generic ODBC guessed a server-specific view catalog");
 TempWorkspace workspace("native_profiles_");const auto directory=workspace.GetSubpath("data");DbEngine engine(directory.u8string());const auto database=engine.CreateDatabase("Typed SQLite");Require(engine.ExecuteQuery(database.id,"CREATE TABLE values_table(id INTEGER PRIMARY KEY, label TEXT DEFAULT 'default', empty TEXT, bytes BLOB, enabled INTEGER)").error.empty(),"Typed fixture create failed");
 TypedRow values={{"label",{DbValueType::Text,"NULL"}},{"empty",{DbValueType::Null,""}},{"bytes",{DbValueType::Blob,std::string("\0\xff",2)}},{"enabled",{DbValueType::Boolean,"false"}}};const auto inserted=engine.InsertTypedReturningRow(database.id,"values_table",values);Require(inserted.success&&inserted.returned.at("id").text=="1","Inserted SQLite identity unavailable");auto rows=engine.GetTableData(database.id,"values_table");Require(rows.typedRows[0].at("label").type==DbValueType::Text&&rows.typedRows[0].at("empty").type==DbValueType::Null&&rows.typedRows[0].at("bytes").text==std::string("\0\xff",2),"NULL/text/BLOB types did not round-trip");auto exported=json::parse(engine.ExportTableData(database.id,"values_table","json"));Require(exported[0]["empty"].is_null()&&exported[0]["bytes"]["$binary"]=="00ff","Typed SQLite export corrupted NULL/BLOB");Require(engine.UpdateTypedRow(database.id,"values_table",{{"id",{DbValueType::Integer,"1"}}},{{"label",{DbValueType::Text,std::string("a\0b",3)}}}),"Typed SQLite update failed");Require(engine.FindTypedRow(database.id,"values_table",{{"id",{DbValueType::Integer,"1"}}}).at("label").text==std::string("a\0b",3),"Embedded NUL text lost");
 Require(engine.ExecuteQuery(database.id,"CREATE TABLE numeric_values(id INTEGER PRIMARY KEY, value REAL NOT NULL)").error.empty(),"SQLite numeric fixture could not be created");
 const std::vector<double> numericValues{349.99,std::nextafter(1.0,2.0),1.2345678901234567,1e-300,std::numeric_limits<double>::denorm_min(),1e300,std::numeric_limits<double>::max(),-349.99};
 for(size_t i=0;i<numericValues.size();++i)Require(engine.InsertTypedRow(database.id,"numeric_values",{{"id",{DbValueType::Integer,std::to_string(i+1)}},{"value",{DbValueType::Real,json(numericValues[i]).dump()}}}),"SQLite real bind failed");
 const auto numericRows=engine.GetTableData(database.id,"numeric_values",1,25,"id","asc");Require(numericRows.error.empty()&&numericRows.rows.size()==numericValues.size()&&numericRows.rows[0].at("value")=="349.99","SQLite price still displays excess binary rounding digits");
 const auto numericQuery=engine.ExecuteQuery(database.id,"SELECT id,value FROM numeric_values ORDER BY id");Require(numericQuery.error.empty()&&numericQuery.rows[0].at("value")=="349.99","SQLite query display differs from grid numeric formatting");
 const auto numericExport=json::parse(engine.ExportTableData(database.id,"numeric_values","json","","id","asc"));
 for(size_t i=0;i<numericValues.size();++i){const auto& value=numericRows.typedRows[i].at("value");Require(value.type==DbValueType::Real,"SQLite float lost its typed Real tag");const double parsedValue=DbValueJson(value).get<double>(),queryValue=DbValueJson(numericQuery.typedRows[i].at("value")).get<double>(),exportValue=numericExport[i]["value"].get<double>();Require(std::memcmp(&parsedValue,&numericValues[i],sizeof(double))==0&&std::memcmp(&queryValue,&numericValues[i],sizeof(double))==0&&std::memcmp(&exportValue,&numericValues[i],sizeof(double))==0,"SQLite shortest numeric text changed a double during grid/query/JSON export");const TypedRow key{{"id",{DbValueType::Integer,std::to_string(i+1)}}};Require(engine.UpdateTypedRow(database.id,"numeric_values",key,{{"value",value}}),"SQLite real rebind failed");const double rebound=DbValueJson(engine.FindTypedRow(database.id,"numeric_values",key).at("value")).get<double>();Require(std::memcmp(&rebound,&numericValues[i],sizeof(double))==0,"SQLite numeric display changed the value on rebind");}
 const auto negativeZero=engine.ExecuteQuery(database.id,"SELECT -0.0 AS value");Require(negativeZero.error.empty()&&negativeZero.rows[0].at("value")=="-0.0"&&std::signbit(DbValueJson(negativeZero.typedRows[0].at("value")).get<double>()),"SQLite negative-zero sign was lost during numeric formatting");
 ConnectionProfile readonly;readonly.name="Read-only";readonly.path=database.path;readonly.readOnly=true;const auto saved=engine.SaveConnection(readonly,false);Require(!saved.connected,"Save(false) connected unexpectedly");Require(engine.ExecuteQuery(saved.id,"UPDATE values_table SET label='changed'").error.find("read-only")!=std::string::npos,"Read-only SQL mutation accepted");Require(!engine.GetSchema(saved.id).tables[0].editable,"Read-only grid marked editable");Require(engine.ExplainQuery(saved.id,"SELECT * FROM values_table").error.empty(),"Read-only EXPLAIN rejected");Reject([&]{engine.InsertTypedRow(saved.id,"values_table",{});},"Read-only typed insert accepted");Require(engine.DisconnectDatabase(saved.id),"SQLite disconnect failed");for(const auto& info:engine.ListDatabases())if(info.id==saved.id)Require(!info.connected,"SQLite disconnected marker incorrect");Require(engine.DeleteDatabase(saved.id)&&fs::exists(fs::u8path(database.path)),"Detaching profile deleted external SQLite file");
 ConnectionProfile secret;secret.name="Protected settings";secret.type="odbc";secret.odbcConnectionString="Driver={synthetic-native-driver};";secret.username="fake-native-user";secret.password="fake-native-profile-secret";secret.optionsJson=R"({"AppName":"safe-option","Password":"fake-option-secret"})";secret.persistCredentials=true;const auto protectedInfo=engine.SaveConnection(secret);const auto disk=Read(directory/"connections.json");Require(disk.find("fake-")==std::string::npos&&disk.find("synthetic-native-driver")==std::string::npos&&disk.find("dpapi:v1:")!=std::string::npos,"Native profile settings stored plaintext");DbEngine restart(directory.u8string());auto loaded=restart.GetConnectionProfile(protectedInfo.id);Require(loaded.password==secret.password&&loaded.username==secret.username&&loaded.optionsJson==json::parse(secret.optionsJson).dump(),"Protected native profile failed to round-trip");
 secret.id.clear();secret.name="Session-only";secret.persistCredentials=false;const auto session=engine.SaveConnection(secret);DbEngine another(directory.u8string());auto sessionProfile=another.GetConnectionProfile(session.id);Require(sessionProfile.password.empty()&&sessionProfile.odbcConnectionString.empty()&&sessionProfile.sessionCredentials&&json::parse(sessionProfile.optionsJson).at("AppName")=="safe-option"&&!json::parse(sessionProfile.optionsJson).contains("Password"),"Session credential stripping removed safe options or leaked secrets");Require(!another.ExecuteQuery(session.id,"SELECT 1").error.empty(),"Restarted session connected without re-entry");
 secret.id.clear();secret.name="ODBC short credential key";secret.optionsJson=R"({"PWD":"synthetic-pwd-value","AppName":"safe-option"})";const auto shortKey=engine.SaveConnection(secret,false);DbEngine optionsRestart(directory.u8string());const auto optionProfile=optionsRestart.GetConnectionProfile(shortKey.id);Require(optionProfile.sessionCredentials&&!json::parse(optionProfile.optionsJson).contains("PWD"),"ODBC PWD option survived session-only restart");
 Require(DecodeConnectionComponent("fake%2Bencoded+literal")=="fake+encoded+literal","Database URI plus sign decoded as form whitespace");ConnectionProfile diagnostics;diagnostics.url="mongodb://synthetic-user:fake%2Duri%2Bvalue+tail@localhost/test?access_token=fake%2Dquery%2Bvalue+tail";diagnostics.odbcConnectionString="DRIVER={fake};PWD={fake;brace}}value};";diagnostics.optionsJson=R"({"nested":{"PWD":"fake-option-value"}})";const auto scrubbed=ScrubConnectionError("Driver rejected fake-uri+value+tail / fake-query+value+tail / fake;brace}value / fake-option-value",diagnostics);Require(scrubbed.find("fake-")==std::string::npos&&scrubbed.find("fake;")==std::string::npos,"Driver diagnostic exposed an embedded connection credential");
 ConnectionProfile deferred;deferred.type="odbc";deferred.name="Environment reference";deferred.odbcEnv="DATAFORGE_TEST_UNSET_ODBC_REFERENCE_721CF";Require(!engine.SaveConnection(deferred,false).connected,"Disconnected environment profile could not be saved");
 ConnectionProfile mongo;mongo.type="mongodb";mongo.name="Read-only Mongo policy";mongo.database="synthetic_no_service";mongo.readOnly=true;const auto mongoInfo=engine.SaveConnection(mongo,false);for(const auto& stage:json::array({json{{"$out","blocked"}},json{{"$facet",{{"nested",json::array({json{{"$merge","blocked"}}})}}}}})){auto rejection=engine.ExecuteQuery(mongoInfo.id,json{{"collection","synthetic"},{"operation","aggregate"},{"pipeline",json::array({stage})}}.dump());Require(rejection.error.find("read-only")!=std::string::npos,"Mongo aggregate writing stage bypassed read-only policy");}
 const auto detached=engine.CreateDatabase("Keep file after detach");Require(engine.RemoveConnection(detached.id)&&fs::exists(fs::u8path(detached.path)),"Detach removed owned SQLite contents");DbEngine reopened(directory.u8string());for(const auto& info:reopened.ListDatabases())Require(info.id!=detached.id,"Detached local SQLite returned after restart");
 Require(json::parse(engine.FormatQuery(R"({"collection":"sample","filter":{"label":"select"}})","document"))["filter"]["label"]=="select","Mongo formatting changed JSON values");Require(engine.FormatQuery("get 'a key'","keyvalue")=="GET 'a key'","Redis formatting changed command arguments");
 std::atomic_bool cancelled{true};Reject([&]{engine.TestConnection(readonly,&cancelled);},"Cancelled profile test accepted");Reject([&]{engine.InsertTypedRow(database.id,"values_table",{},&cancelled);},"Cancelled typed mutation accepted");Reject([&]{DbValueJson({DbValueType::Integer,"18446744073709551615"});},"Unsigned integer silently overflowed");Require(DbValueFromJson(json{{"$binary","00Ff"},{"$encoding","hex"}}).text==std::string("\0\xff",2),"Binary JSON decode failed");Reject([&]{DbValueFromJson(json{{"$binary","0z"},{"$encoding","hex"}});},"Invalid binary hex accepted");
 auto drivers=engine.ListDrivers();Require(drivers.size()>=17,"Original native driver registry incomplete");Require(std::find_if(drivers.begin(),drivers.end(),[](const auto& item){return item.id=="duckdb"&&item.available;})!=drivers.end(),"Bundled DuckDB driver unavailable");}
void TestNativeDuckDbProvider(){TempWorkspace workspace("native_duckdb_");DbEngine engine(workspace.GetSubpath("data").u8string());ConnectionProfile profile;profile.type="duckdb";profile.name="Native analytical file";profile.path=workspace.GetSubpath("native.duckdb").u8string();profile.create=true;profile.optionsJson=R"({"threads":1,"memory_limit":"256MB"})";Require(engine.TestConnection(profile).find("has not created")!=std::string::npos&&!fs::exists(fs::u8path(profile.path)),"DuckDB Test unexpectedly created file");const auto database=engine.SaveConnection(profile,true);auto created=engine.ExecuteQuery(database.id,"CREATE TABLE parent(id INTEGER PRIMARY KEY); CREATE TABLE child(id INTEGER PRIMARY KEY, parent_id INTEGER REFERENCES parent(id), label VARCHAR, bytes BLOB); INSERT INTO parent VALUES (7)");Require(created.error.empty(),created.error.c_str());Require(engine.InsertTypedRow(database.id,"child",{{"id",{DbValueType::Integer,"1"}},{"parent_id",{DbValueType::Integer,"7"}},{"label",{DbValueType::Null,""}},{"bytes",{DbValueType::Blob,std::string("\0\xff",2)}}}),"Native DuckDB bound insert failed");const auto schema=engine.GetSchema(database.id);auto child=std::find_if(schema.tables.begin(),schema.tables.end(),[](const auto& table){return table.name=="child";});Require(child!=schema.tables.end()&&child->primaryKeys==std::vector<std::string>{"id"}&&child->foreignKeys.size()==1&&!child->ddl.empty(),"DuckDB metadata/ER relationship incomplete");auto rows=engine.GetTableData(database.id,"child");Require(rows.error.empty()&&rows.typedRows[0].at("label").type==DbValueType::Null&&rows.typedRows[0].at("bytes").text==std::string("\0\xff",2),"DuckDB typed grid corrupted value");auto query=engine.ExecuteQuery(database.id,"SELECT 1 AS id,2 AS id; SELECT 3 AS tail");Require(query.error.empty()&&query.resultSets.size()==2&&query.resultSets[0].rows[0].at("id (2)")=="2","DuckDB multiple results/duplicate labels failed");Require(engine.UpdateTypedRow(database.id,"child",{{"id",{DbValueType::Integer,"1"}}},{{"label",{DbValueType::Text,"literal 100%_!"}}}),"DuckDB typed update failed");rows=engine.GetTableData(database.id,"child",1,25,"id","asc","100%_!");Require(rows.error.empty()&&rows.totalRows==1,"DuckDB literal LIKE escaping incorrect");auto exported=json::parse(engine.ExportTableData(database.id,"child","json"));Require(exported[0]["bytes"]["$binary"]=="00ff","DuckDB binary export incorrect");
 Require(engine.ExecuteQuery(database.id,"SELECT current_setting('threads') AS threads").rows[0].at("threads")=="1","DuckDB native config ignored");auto invalidOptions=profile;invalidOptions.optionsJson=R"({"native_nonexistent_option":true})";Reject([&]{engine.TestConnection(invalidOptions);},"Unknown DuckDB option silently ignored"); const auto failed=engine.ExecuteQuery(database.id,"INSERT INTO parent VALUES (9); INSERT INTO missing VALUES(1)");Require(!failed.error.empty()&&engine.ExecuteQuery(database.id,"SELECT COUNT(*) AS total FROM parent WHERE id=9").rows[0].at("total")=="0","DuckDB failed batch left partial write");std::atomic_bool cancellation{false};QueryResult cancelled;std::thread worker([&]{cancelled=engine.ExecuteQuery(database.id,"SELECT SUM(i) FROM range(1000000000000) t(i)",10,&cancellation);});Sleep(100);const auto start=std::chrono::steady_clock::now();cancellation=true;worker.join();Require(cancelled.error.find("cancel")!=std::string::npos&&std::chrono::steady_clock::now()-start<std::chrono::seconds(2),"DuckDB query did not cancel promptly");Require(engine.DisconnectDatabase(database.id),"DuckDB disconnect failed");profile=engine.GetConnectionProfile(database.id);profile.readOnly=true;engine.SaveConnection(profile,true);Require(!engine.ExecuteQuery(database.id,"DELETE FROM child").error.empty(),"DuckDB readonly mutation accepted");Require(engine.DeleteDatabase(database.id)&&fs::exists(fs::u8path(profile.path)),"DuckDB profile detach removed external file");}
void TestNativeRedisProtocol(){RespFixture fixture;TempWorkspace workspace("native_redis_");DbEngine engine(workspace.GetSubpath("data").u8string());ConnectionProfile profile;profile.type="redis";profile.name="Loopback RESP fixture";profile.host="localhost";profile.port=fixture.Port();profile.sslMode="disable";profile.timeoutSec=3;const auto database=engine.SaveConnection(profile,true);Require(engine.GetSchema(database.id).tables[0].rowCount==2,"Native Redis DBSIZE/schema failed");auto query=engine.ExecuteQuery(database.id,"GET binary");Require(query.error.empty()&&query.typedRows[0].at("result").type==DbValueType::Blob&&query.typedRows[0].at("result").text==std::string("\0\xff",2),"Native RESP binary data corrupted");Require(engine.InsertTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"new-key"}},{"value",{DbValueType::Text,"two words"}}}),"Redis SET NX failed");Reject([&]{engine.InsertTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"new-key"}}});},"Redis insert overwrote existing key");Require(engine.UpdateTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"new-key"}}},{{"value",{DbValueType::Text,"changed"}}}),"Redis SET XX KEEPTTL failed");auto data=engine.GetTableData(database.id,"keys",1,25);Require(data.error.empty()&&data.totalRows==3,"Native Redis SCAN/grid failed");auto exported=json::parse(engine.ExportTableData(database.id,"keys","json"));Require(exported.size()==3,"Redis export incomplete");Require(engine.DeleteTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"new-key"}}}),"Redis DEL failed");Require(!engine.ExecuteQuery(database.id,"CONFIG GET *").error.empty(),"Redis administrative command accepted");Require(engine.ExecuteQuery(database.id,R"({"command":"GET","args":["alpha"]})").rows[0].at("result")=="first","Redis JSON command failed");
 Reject([&]{engine.UpdateTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"alpha"}}},{{"ttl",{DbValueType::Integer,"60"}}});},"Redis metadata-only edit accepted");Reject([&]{engine.UpdateTypedRow(database.id,"keys",{{"key",{DbValueType::Text,"alpha"}}},{{"key",{DbValueType::Text,"alpha"}}});},"Redis partial edit erased existing value");Require(engine.ExecuteQuery(database.id,"GET alpha").rows[0].at("result")=="first","Rejected Redis edit changed data");
 profile=engine.GetConnectionProfile(database.id);profile.readOnly=true;engine.SaveConnection(profile);Require(!engine.ExecuteQuery(database.id,"SET alpha overwritten").error.empty()&&engine.ExecuteQuery(database.id,"GET alpha").rows[0].at("result")=="first","Redis readonly command guard failed");profile.readOnly=false;engine.SaveConnection(profile);std::atomic_bool cancel{false};QueryResult result;std::thread worker([&]{result=engine.ExecuteQuery(database.id,"SLOW",1,&cancel);});Sleep(100);const auto start=std::chrono::steady_clock::now();cancel=true;worker.join();Require(result.error.find("cancel")!=std::string::npos&&std::chrono::steady_clock::now()-start<std::chrono::seconds(1),"Redis socket cancellation failed");RespFixture complex(true);profile.id.clear();profile.name="Complex RESP fixture";profile.port=complex.Port();profile.optionsJson=R"({"client_name":"native-fixture","socket_timeout":3,"socket_connect_timeout":3})";const auto complete=engine.SaveConnection(profile,true);const auto preview=engine.GetTableData(complete.id,"keys",1,25);Require(preview.error.empty()&&preview.truncated,"Sampled Redis complex values not flagged");const auto full=json::parse(engine.ExportTableData(complete.id,"keys","json"));size_t collections=0;for(const auto& row:full)if(row["type"]!="string"){Require(row["value"].is_array()&&row["value"].size()==250,"Redis export silently truncated a complex value");++collections;}Require(collections==4,"Redis complex export missed key types");profile.optionsJson=R"({"unsupported_native_option":true})";Reject([&]{engine.TestConnection(profile);},"Unknown Redis option silently ignored");}
void TestNativeMockRestService(){TempWorkspace workspace("native_mock_");DbEngine engine(workspace.GetSubpath("data").u8string());const auto database=engine.CreateDatabase("Mock SQLite");Require(engine.ExecuteQuery(database.id,"CREATE TABLE records(id INTEGER PRIMARY KEY, label TEXT, value REAL, optional TEXT, bytes BLOB); CREATE TABLE pairs(a INT,b INT,PRIMARY KEY(a,b))").error.empty(),"Mock fixture create failed");NativeMockServer server(&engine);const auto port=server.Start(0);Require(port&&server.IsRunning(),"Native mock listener did not start");auto inserted=Request(server,database.id,"records","POST",{{"label","first"},{"value",1.5},{"optional",nullptr},{"bytes",{{"$binary","00ff"},{"$encoding","hex"}}}});Require(inserted.error.empty()&&inserted.statusCode==201,"Native mock POST failed");const auto response=json::parse(inserted.body);Require(response["last_row_id"]==1,"Mock POST inserted identity incorrect");auto get=Request(server,database.id,"records/1");auto record=json::parse(get.body);Require(get.statusCode==200&&record["data"]["optional"].is_null()&&record["data"]["bytes"]["$binary"]=="00ff","Native mock record types incorrect");auto patch=Request(server,database.id,"records/1","PATCH",{{"label","patched"}});Require(patch.statusCode==200&&json::parse(Request(server,database.id,"records/1").body)["data"]["label"]=="patched","Native mock PATCH failed");auto list=Request(server,database.id,"records","GET",{},"&page=1&page_size=1&sort=id&sort_dir=desc&search=patched");Require(list.statusCode==200&&json::parse(list.body)["total"]==1,"Mock list paging/search aliases failed");Require(Request(server,database.id,"pairs/1").statusCode==400,"Mock composite-key record endpoint accepted");Require(Request(server,database.id,"records/999").statusCode==404,"Mock missing record status incorrect");Require(Request(server,database.id,"records/1","DELETE").statusCode==200&&Request(server,database.id,"records/1").statusCode==404,"Native mock DELETE failed");
 ConnectionProfile duck;duck.type="duckdb";duck.name="Mock DuckDB SQL provider";duck.path=workspace.GetSubpath("mock.duckdb").u8string();duck.create=true;const auto remote=engine.SaveConnection(duck,true);Require(engine.ExecuteQuery(remote.id,"CREATE SEQUENCE ids START 100; CREATE TABLE remote_records(id BIGINT PRIMARY KEY DEFAULT nextval('ids'), label VARCHAR, optional VARCHAR, bytes BLOB)").error.empty(),"DuckDB mock fixture could not be created");auto remotePost=Request(server,remote.id,"remote_records","POST",{{"label","remote"},{"optional",nullptr},{"bytes",{{"$binary","00ff"},{"$encoding","hex"}}}});Require(remotePost.statusCode==201&&json::parse(remotePost.body)["last_row_id"]==100,"SQL provider mock insert identity failed");auto remoteRow=Request(server,remote.id,"remote_records/100");Require(remoteRow.statusCode==200&&json::parse(remoteRow.body)["data"]["bytes"]["$binary"]=="00ff","SQL provider bound mock record lookup failed");Require(Request(server,remote.id,"remote_records/100","PUT",{{"label","put"}}).statusCode==200&&Request(server,remote.id,"remote_records/100","PATCH",{{"label","patched"}}).statusCode==200,"SQL provider mock updates failed");Require(json::parse(Request(server,remote.id,"remote_records").body)["total"]==1,"SQL provider mock list failed");const auto malformedKey=Request(server,remote.id,"remote_records/100%27%20OR%201%3D1");Require((malformedKey.statusCode==400||malformedKey.statusCode==404)&&Request(server,remote.id,"remote_records/100").statusCode==200,"SQL provider mock record id bypassed bound lookup");Require(Request(server,remote.id,"remote_records/100","DELETE").statusCode==200&&Request(server,remote.id,"remote_records/100").statusCode==404,"SQL provider mock delete failed");
 NativeSocket malformed;malformed.Connect("127.0.0.1",port,false,"",2,nullptr);const std::string raw="POST /api/mock/data/records?db="+database.id+" HTTP/1.1\r\nHost: localhost\r\nContent-Length: 2\r\nContent-Length: 2\r\n\r\n{}";malformed.Write(raw.data(),raw.size());char bytes[1024]{};const auto count=malformed.Read(bytes,sizeof(bytes));Require(std::string(bytes,count).find("400 Bad Request")!=std::string::npos,"Mock duplicate Content-Length accepted");
 NativeSocket idle;idle.Connect("127.0.0.1",port,false,"",2,nullptr);const std::string partial="GET / HTTP/1.1\r\n";idle.Write(partial.data(),partial.size());Sleep(50);const auto start=std::chrono::steady_clock::now();server.Stop();Require(!server.IsRunning()&&server.Port()==0&&std::chrono::steady_clock::now()-start<std::chrono::seconds(1),"Mock stop blocked on idle client");Require(server.Start(0)!=0,"Mock restart failed");server.Stop();}
