#include "CodeGen.h"
#include "CurlParser.h"
#include "VariableResolver.h"
#include <stdexcept>
#include <algorithm>
#include <nlohmann/json.hpp>
#include "quickjs.h"

using namespace native_app;
namespace {
void RequireSnippet(bool value,const char* message){if(!value)throw std::runtime_error(message);}
void CompileJavaScript(const std::string& text){
    auto* runtime=JS_NewRuntime();if(!runtime)throw std::runtime_error("Cannot allocate snippet parser.");auto* context=JS_NewContext(runtime);if(!context){JS_FreeRuntime(runtime);throw std::runtime_error("Cannot allocate snippet context.");}
    auto result=JS_Eval(context,text.data(),text.size(),"generated-snippet.js",JS_EVAL_TYPE_GLOBAL|JS_EVAL_FLAG_COMPILE_ONLY);const bool parsed=!JS_IsException(result);JS_FreeValue(context,result);JS_FreeContext(context);JS_FreeRuntime(runtime);RequireSnippet(parsed,"Generated JavaScript has invalid syntax.");
}
}
void TestNativeSnippetBehavior(){
    ApiRequest request;request.url="https://example.invalid/items/{id}#result";request.method=HttpMethod::OPTIONS;request.pathParams.push_back({"id","a b",true,""});request.params.push_back({"q","a & b",true,""});request.params.push_back({"disabled","hidden",false,""});request.auth.type=AuthType::Bearer;request.auth.token="native-fixture";request.options.followRedirects=false;request.options.verifyTls=false;request.options.timeoutSec=4.5;request.headers.push_back({"Skipped","hidden",false,""});
    const auto curl=CodeGen::Generate(request,"curl");const auto parsed=CurlParser::Parse(curl);const auto prepared=VariableResolver::PrepareRequest(parsed,{});RequireSnippet(parsed.method==HttpMethod::OPTIONS,"Generated cURL lost OPTIONS.");RequireSnippet(prepared.url=="https://example.invalid/items/a%20b?q=a%20%26%20b#result","Generated/imported cURL changed encoded path/query/fragment.");RequireSnippet(parsed.auth.type==AuthType::Bearer&&parsed.auth.token=="native-fixture"&&std::any_of(prepared.headers.begin(),prepared.headers.end(),[](const auto& header){return header.key=="Authorization"&&header.value=="Bearer native-fixture";}),"Generated/imported cURL omitted authentication.");RequireSnippet(!parsed.options.followRedirects&&!parsed.options.verifyTls&&parsed.options.timeoutSec==4.5,"Generated/imported cURL changed native request options.");RequireSnippet(curl.find("hidden")==std::string::npos,"Disabled values were generated.");
    request.method=HttpMethod::HEAD;const auto head=CodeGen::Generate(request,"python");RequireSnippet(head.find("requests.request(\"HEAD\"")!=std::string::npos,"Generated Python cannot send HEAD.");RequireSnippet(head.find("allow_redirects=False, verify=False")!=std::string::npos,"Generated Python lost redirect/TLS options.");
    request.body.type=BodyType::Json;request.body.content=R"({"body":true})";RequireSnippet(CodeGen::Generate(request,"python").find("json=payload")!=std::string::npos,"Generated HEAD snippet dropped the configured body.");request.method=HttpMethod::GET;RequireSnippet(CodeGen::Generate(request,"curl").find("--data-raw")!=std::string::npos,"Generated GET snippet dropped the configured body.");CompileJavaScript(CodeGen::Generate(request,"axios"));bool fetchRejected=false;try{(void)CodeGen::Generate(request,"fetch");}catch(const std::exception&){fetchRejected=true;}RequireSnippet(fetchRejected,"Browser fetch generated an unsupported GET body instead of an actionable error.");
    request.method=HttpMethod::POST;request.body.type=BodyType::Json;request.body.content=R"({"nested":[true,false,null,{"value":true}],"message":"Unicode \ud83d\ude80"})";const auto python=CodeGen::Generate(request,"python");RequireSnippet(python.find("[True, False, None, {")!=std::string::npos,"Generated Python used invalid JSON booleans or null.");RequireSnippet(python.find("json=payload")!=std::string::npos,"Generated Python omitted JSON payload.");CompileJavaScript(CodeGen::Generate(request,"fetch"));CompileJavaScript(CodeGen::Generate(request,"axios"));
    request.body.type=BodyType::FormData;request.body.formItems={{"value","@literal & field",true,"text","","text/plain",""},{"upload","",true,"file","example.bin","application/octet-stream","QQBC"},{"disabled","hidden",false,"text","","",""}};
    const auto formCurl=CodeGen::Generate(request,"curl");RequireSnippet(formCurl.find("--form-string 'value=@literal & field'")!=std::string::npos,"cURL text form fields could be interpreted as filenames.");RequireSnippet(formCurl.find("-F 'upload=@example.bin'")!=std::string::npos,"cURL omitted file multipart field.");
    const auto importedForm=CurlParser::Parse(formCurl);RequireSnippet(importedForm.body.type==BodyType::FormData&&importedForm.body.formItems.size()==2&&importedForm.body.formItems[0].value=="@literal & field"&&importedForm.body.formItems[0].type=="text"&&importedForm.body.formItems[1].type=="file"&&importedForm.body.formItems[1].filename=="example.bin"&&importedForm.body.formItems[1].contentBase64.empty(),"Multipart cURL import changed literal fields or file references.");
    const auto formPython=CodeGen::Generate(request,"python");RequireSnippet(formPython.find("base64.b64decode(\"QQBC\")")!=std::string::npos&&formPython.find("files=files")!=std::string::npos,"Python multipart omitted attached binary bytes.");
    const auto fetch=CodeGen::Generate(request,"fetch"),axios=CodeGen::Generate(request,"axios");RequireSnippet(fetch.find("Uint8Array.from(atob(\"QQBC\")")!=std::string::npos,"Fetch multipart omitted attached binary bytes.");RequireSnippet(axios.find("Buffer.from(\"QQBC\", 'base64')")!=std::string::npos,"Axios multipart omitted attached binary bytes.");RequireSnippet(fetch.find("Content-Type")==std::string::npos,"Multipart snippet forced an invalid boundary header.");CompileJavaScript(fetch);CompileJavaScript(axios);
    request.body.type=BodyType::UrlEncoded;request.body.formItems={{"a b","x+y&z",true},{"disabled","hidden",false}};RequireSnippet(CodeGen::Generate(request,"fetch").find("a%20b=x%2By%26z")!=std::string::npos,"Form URL encoding was lost.");
}
